export interface VerbTenseExamples {
  present: [sentence: string, translation: string]
  pastZh: string
  continuous?: [sentence: string, translation: string]
  continuousNote?: string
  perfectZh: string
}

export const VERB_TENSE_EXAMPLES: Record<string, VerbTenseExamples> = {
  be: { present: ["I am usually at home after school.", "我放学后通常在家。"], pastZh: "米娅昨天在家。", continuousNote: "be 表示身份、状态或位置时，通常不使用进行时。", perfectZh: "我去过伦敦两次。" },
  become: { present: ["The days become warmer in spring.", "春天天气逐渐变暖。"], pastZh: "天色变暗了。", continuous: ["The sky was becoming darker when we left.", "我们离开时，天色正逐渐变暗。"], perfectZh: "她变得更自信了。" },
  begin: { present: ["School begins at eight every day.", "学校每天八点开始上课。"], pastZh: "课程九点开始了。", continuous: ["The film was beginning when we arrived.", "我们到达时电影正要开始。"], perfectZh: "电影已经开始了。" },
  break: { present: ["Be careful, or you may break the glass.", "小心，否则你可能打破玻璃。"], pastZh: "利奥昨天弄坏了眼镜。", continuous: ["Tom was breaking the chocolate into pieces when I came in.", "我进来时，汤姆正在把巧克力掰成小块。"], perfectZh: "有人打破了窗户。" },
  build: { present: ["They build new houses in this town every year.", "他们每年都在这个镇上建新房。"], pastZh: "他们在2010年建了这座桥。", continuous: ["They were building the bridge when we visited.", "我们参观时，他们正在建那座桥。"], perfectZh: "我们已经做了一个飞机模型。" },
  burn: { present: ["Dry wood burns quickly.", "干木头燃烧得很快。"], pastZh: "我的手被平底锅烫伤了。", continuous: ["The fire was burning when we arrived.", "我们到达时火正在燃烧。"], perfectZh: "太阳晒伤了我的脸。" },
  buy: { present: ["We buy fresh bread every Saturday.", "我们每周六买新鲜面包。"], pastZh: "爸爸昨天买了一些水果。", continuous: ["I was buying the tickets when you called.", "你打电话时我正在买票。"], perfectZh: "我们已经买好票了。" },
  catch: { present: ["I catch the eight o'clock bus every morning.", "我每天早上赶八点的公交车。"], pastZh: "我赶上了最后一班回家的公交车。", continuous: ["She was catching the ball when she fell.", "她接球时摔倒了。"], perfectZh: "猫抓到了一只老鼠。" },
  choose: { present: ["I usually choose the blue one.", "我通常选择蓝色的那个。"], pastZh: "艾米选择了蓝色连衣裙。", continuous: ["We were choosing a present when Dad arrived.", "爸爸到达时我们正在挑礼物。"], perfectZh: "你选好队伍了吗？" },
  come: { present: ["My grandparents come every Sunday.", "我的祖父母每周日都来。"], pastZh: "本来参加了我的聚会。", continuous: ["I was coming home when it started to rain.", "开始下雨时我正在回家。"], perfectZh: "今年春天来得很早。" },
  cost: { present: ["This book costs ten pounds.", "这本书十英镑。"], pastZh: "这本书花了十英镑。", continuousNote: "cost 表示价格或花费时通常是状态，不使用进行时。", perfectZh: "这次旅行已经花了我们很多钱。" },
  cut: { present: ["I cut fruit for breakfast every morning.", "我每天早饭都切水果。"], pastZh: "她仔细地剪了纸。", continuous: ["She was cutting the cake when I arrived.", "我到达时她正在切蛋糕。"], perfectZh: "我已经把蛋糕切成六块了。" },
  do: { present: ["I do my homework after dinner.", "我晚饭后做作业。"], pastZh: "我们晚饭后做了作业。", continuous: ["I was doing my homework when Ben called.", "本打电话时我正在做作业。"], perfectZh: "汤姆已经洗完碗了。" },
  draw: { present: ["I draw in my notebook every day.", "我每天都在笔记本上画画。"], pastZh: "露西画了一幅她的狗的画。", continuous: ["Lucy was drawing when the teacher came in.", "老师进来时露西正在画画。"], perfectZh: "他已经给我们画了一张地图。" },
  dream: { present: ["I often dream about flying.", "我经常梦见飞翔。"], pastZh: "我昨晚梦见了飞翔。", continuous: ["I was dreaming when the alarm rang.", "闹钟响时我正在做梦。"], perfectZh: "她一直梦想成为一名飞行员。" },
  drink: { present: ["I drink water with every meal.", "我每顿饭都喝水。"], pastZh: "他喝完了所有橙汁。", continuous: ["I was drinking some water when you arrived.", "你到达时我正在喝水。"], perfectZh: "我从未喝过咖啡。" },
  drive: { present: ["Mum drives us to school every day.", "妈妈每天开车送我们上学。"], pastZh: "妈妈开车送我们去了学校。", continuous: ["Dad was driving when the rain started.", "开始下雨时爸爸正在开车。"], perfectZh: "你开过面包车吗？" },
  eat: { present: ["We eat dinner at seven every day.", "我们每天七点吃晚饭。"], pastZh: "我们星期五吃了披萨。", continuous: ["We were eating dinner when the lights went out.", "灯灭时我们正在吃晚饭。"], perfectZh: "萨姆已经吃过午饭了。" },
  fall: { present: ["Leaves fall from the trees in autumn.", "秋天树叶从树上落下。"], pastZh: "杯子掉到了地板上。", continuous: ["Snow was falling when we left home.", "我们离开家时正在下雪。"], perfectZh: "已经下了很多雪。" },
  feel: { present: ["I feel happy when I play outside.", "我在外面玩时感到开心。"], pastZh: "比赛后我感到很累。", continuous: ["I was feeling tired, so I went home.", "我当时觉得累，所以回家了。"], perfectZh: "你有过这么开心的感觉吗？" },
  find: { present: ["I often find shells on this beach.", "我经常在这片海滩上发现贝壳。"], pastZh: "埃拉在沙发下面找到了钥匙。", continuousNote: "find 表示“找到、发现”这一结果时，通常不使用进行时。", perfectZh: "我们已经找到了一个更好的方法。" },
  fly: { present: ["Birds fly south in winter.", "鸟儿冬天向南飞。"], pastZh: "那只鸟飞出了窗户。", continuous: ["We were flying over France when I took this photo.", "我拍这张照片时，我们正飞越法国。"], perfectZh: "我从未坐过直升机。" },
  forget: { present: ["I sometimes forget my keys.", "我有时会忘带钥匙。"], pastZh: "我昨天忘了带伞。", continuous: ["I was forgetting new words quickly, so I made a list.", "我当时很快就忘记新单词，所以列了一张表。"], perfectZh: "她已经忘记我的名字了。" },
  get: { present: ["I get home at six every day.", "我每天六点到家。"], pastZh: "我们六点到家了。", continuous: ["It was getting dark when we left.", "我们离开时天正渐渐变黑。"], perfectZh: "我的网球打得好多了。" },
  give: { present: ["My teacher gives us homework on Fridays.", "老师每周五给我们布置作业。"], pastZh: "姑姑把这块手表送给了我。", continuous: ["The teacher was giving instructions when I arrived.", "我到达时老师正在说明要求。"], perfectZh: "老师已经给了我们额外时间。" },
  go: { present: ["I go to school by bus every day.", "我每天坐公交车上学。"], pastZh: "他们昨天去了博物馆。", continuous: ["We were going home when we saw Mia.", "我们回家时看见了米娅。"], perfectZh: "爸爸去超市了，现在还没回来。" },
  grow: { present: ["Tomatoes grow well here.", "西红柿在这里长得很好。"], pastZh: "小狗长得很快。", continuous: ["The puppy was growing quickly that summer.", "那年夏天小狗正在迅速长大。"], perfectZh: "我们已经在花园里种了西红柿。" },
  have: { present: ["I have cereal for breakfast every day.", "我每天早餐吃麦片。"], pastZh: "我早餐吃了麦片。", continuous: ["We were having dinner when you called.", "你打电话时我们正在吃晚饭。"], perfectZh: "我们度过了美好的一天。", continuousNote: "have 表示“拥有”时通常不用进行时；表示吃饭、活动或经历时可以使用。" },
  hear: { present: ["I hear the school bell every morning.", "我每天早上都听到学校铃声。"], pastZh: "我听到外面有一个奇怪的声音。", continuousNote: "hear 表示自然地“听见”，通常不使用进行时。", perfectZh: "你听说这个消息了吗？" },
  hit: { present: ["Ben hits the ball very hard.", "本击球很用力。"], pastZh: "球撞到了墙上。", continuous: ["We were hitting the ball across the net when it rained.", "下雨时我们正在隔网击球。"], perfectZh: "暴风雨已经袭击了海岸。" },
  hurt: { present: ["My knee hurts after long walks.", "走很久后我的膝盖会疼。"], pastZh: "杰克在比赛中伤了膝盖。", continuous: ["My leg was hurting while I was running.", "我跑步时腿一直疼。"], perfectZh: "我的背受伤了。" },
  keep: { present: ["I keep my books on this shelf.", "我把书放在这个架子上。"], pastZh: "她把那封信保存了很多年。", continuous: ["She was keeping the door open for us.", "她当时正替我们扶着门。"], perfectZh: "我一直替你保守秘密。" },
  know: { present: ["I know the answer now.", "我现在知道答案。"], pastZh: "我立刻就知道了答案。", continuousNote: "know 表示“知道、认识”，是状态动词，通常不使用进行时。", perfectZh: "我们认识五年了。" },
  learn: { present: ["We learn new words every week.", "我们每周学习新单词。"], pastZh: "我们在学校学习了太空知识。", continuous: ["We were learning about space when the bell rang.", "铃响时我们正在学习太空知识。"], perfectZh: "我今天已经学会了十个新单词。" },
  leave: { present: ["The train leaves at seven every morning.", "火车每天早上七点出发。"], pastZh: "火车七点离开了。", continuous: ["We were leaving the house when it began to rain.", "开始下雨时我们正要离开家。"], perfectZh: "有人把一个包落在这里了。" },
  let: { present: ["Mum lets me play outside after school.", "妈妈允许我放学后在外面玩。"], pastZh: "妈妈允许我晚睡。", continuous: ["The teacher was letting everyone choose a book.", "老师当时让每个人选择一本书。"], perfectZh: "他们已经允许我们使用花园。" },
  lie: { present: ["I never lie to my parents.", "我从不对父母撒谎。"], pastZh: "他谎报了年龄。", continuous: ["He was lying when he told that story.", "他说那个故事时正在撒谎。"], perfectZh: "她从未对我撒过谎。" },
  lose: { present: ["I often lose my pencils.", "我经常弄丢铅笔。"], pastZh: "我们队输掉了比赛。", continuous: ["Our team was losing when Sam scored.", "萨姆得分时我们队正处于落后。"], perfectZh: "我把手机弄丢了。" },
  make: { present: ["We make pancakes on Sundays.", "我们星期日做煎饼。"], pastZh: "我们昨天做了一个蛋糕。", continuous: ["We were making a cake when Dad came home.", "爸爸回家时我们正在做蛋糕。"], perfectZh: "埃拉已经交到了一位新朋友。" },
  mean: { present: ["This word means 'very small'.", "这个词的意思是“非常小”。"], pastZh: "我本来打算给你打电话。", continuousNote: "mean 表示“意思是”或“意味着”时是状态动词，通常不使用进行时。", perfectZh: "这对我来说一直意义重大。" },
  meet: { present: ["I meet my friends after school on Fridays.", "我每周五放学后见朋友。"], pastZh: "我在车站遇见了阿里。", continuous: ["I was meeting Ali when you saw me.", "你看见我时我正要和阿里见面。"], perfectZh: "你见过名人吗？" },
  pay: { present: ["Dad pays for lunch on Saturdays.", "爸爸星期六付午餐钱。"], pastZh: "爸爸付了餐费。", continuous: ["I was paying for the tickets when you called.", "你打电话时我正在付票钱。"], perfectZh: "我们已经付过票钱了。" },
  put: { present: ["I put my bag by the door every day.", "我每天把书包放在门边。"], pastZh: "我把牛奶放进了冰箱。", continuous: ["I was putting the milk away when Mum arrived.", "妈妈到达时我正在收好牛奶。"], perfectZh: "她已经穿上外套了。" },
  read: { present: ["I read before bed every night.", "我每天晚上睡前阅读。"], pastZh: "我上周读了那个故事。", continuous: ["I was reading when the lights went out.", "灯灭时我正在阅读。"], perfectZh: "你读过这本书吗？" },
  ride: { present: ["I ride my bike to school every day.", "我每天骑自行车上学。"], pastZh: "我们在公园里骑了自行车。", continuous: ["We were riding our bikes when it started to rain.", "开始下雨时我们正在骑自行车。"], perfectZh: "你骑过马吗？" },
  run: { present: ["I run in the park every morning.", "我每天早上在公园跑步。"], pastZh: "利奥昨天跑了五公里。", continuous: ["Leo was running when he hurt his knee.", "利奥伤到膝盖时正在跑步。"], perfectZh: "她今年已经参加了三场赛跑。" },
  say: { present: ["I always say hello to my neighbours.", "我总是向邻居问好。"], pastZh: "他向每个人问了好。", continuous: ["I was saying goodbye when the bus arrived.", "公交车到达时我正在道别。"], perfectZh: "我已经道过歉了。" },
  see: { present: ["I see my cousins every weekend.", "我每个周末都见表兄弟姐妹。"], pastZh: "我们昨天看到了一道彩虹。", continuousNote: "see 表示自然地“看见”时，通常不使用进行时。", perfectZh: "我从未见过鲸鱼。" },
  sell: { present: ["They sell fruit at this market.", "他们在这个市场卖水果。"], pastZh: "他们卖掉了旧车。", continuous: ["They were selling cakes when we arrived.", "我们到达时他们正在卖蛋糕。"], perfectZh: "商店已经卖完了所有蛋糕。" },
  send: { present: ["I send Grandma a message every Sunday.", "我每周日给奶奶发消息。"], pastZh: "我昨天给你发了一封电子邮件。", continuous: ["I was sending the email when the computer stopped.", "电脑停止运行时我正在发送邮件。"], perfectZh: "她已经寄出了包裹。" },
  show: { present: ["The guide shows visitors around every morning.", "导游每天上午带游客参观。"], pastZh: "马克斯给我看了他的新自行车。", continuous: ["Max was showing me his bike when Dad arrived.", "爸爸到达时马克斯正在给我看他的自行车。"], perfectZh: "导游已经带我们参观了古堡。" },
  shut: { present: ["I shut the window before bed every night.", "我每天晚上睡前关窗。"], pastZh: "她轻轻地关上了门。", continuous: ["She was shutting the door when the cat ran in.", "猫跑进来时她正在关门。"], perfectZh: "图书馆今天已经提前关门了。" },
  sing: { present: ["We sing in music class every Friday.", "我们每周五在音乐课上唱歌。"], pastZh: "玛雅在音乐会上唱了歌。", continuous: ["Maya was singing when we entered the hall.", "我们进入大厅时玛雅正在唱歌。"], perfectZh: "我们以前唱过这首歌。" },
  sit: { present: ["I sit next to Ben in class.", "我上课时坐在本旁边。"], pastZh: "我坐在本旁边。", continuous: ["We were sitting outside when it started to rain.", "开始下雨时我们正坐在外面。"], perfectZh: "她整个上午都坐在那里。" },
  sleep: { present: ["I sleep for nine hours every night.", "我每天晚上睡九个小时。"], pastZh: "宝宝睡了十个小时。", continuous: ["The baby was sleeping when we got home.", "我们到家时宝宝正在睡觉。"], perfectZh: "我从未在帐篷里睡过。" },
  speak: { present: ["I speak English at school every day.", "我每天在学校说英语。"], pastZh: "我昨天和老师谈过了。", continuous: ["I was speaking to Mia when the bell rang.", "铃响时我正在和米娅说话。"], perfectZh: "你和米娅谈过了吗？" },
  spell: { present: ["I spell new words aloud in class.", "我在课堂上大声拼读新单词。"], pastZh: "他拼错了我的名字。", continuous: ["I was spelling the word when the bell rang.", "铃响时我正在拼那个单词。"], perfectZh: "你把每个单词都拼对了。" },
  spend: { present: ["We spend Sundays with our grandparents.", "我们星期日和祖父母一起度过。"], pastZh: "我们在海滩度过了星期日。", continuous: ["We were spending the day at the beach when it rained.", "下雨时我们正在海滩度过一天。"], perfectZh: "我已经花光了零花钱。" },
  stand: { present: ["I stand near the door on the bus.", "我坐公交车时站在门附近。"], pastZh: "他们站在电影院外面。", continuous: ["They were standing outside when we arrived.", "我们到达时他们正站在外面。"], perfectZh: "他已经在那里站了一个小时。" },
  steal: { present: ["Thieves sometimes steal bicycles here.", "小偷有时会在这里偷自行车。"], pastZh: "有人偷了我的自行车。", continuous: ["The thief was stealing the bike when the police arrived.", "警察到达时小偷正在偷自行车。"], perfectZh: "小偷已经偷走了那幅画。" },
  swim: { present: ["I swim every Saturday morning.", "我每周六上午游泳。"], pastZh: "我们昨天在湖里游了泳。", continuous: ["We were swimming when it began to rain.", "开始下雨时我们正在游泳。"], perfectZh: "我从未在海里游过泳。" },
  take: { present: ["I take the bus to school every day.", "我每天坐公交车上学。"], pastZh: "我坐公交车去了学校。", continuous: ["Dad was taking photos when I called him.", "我叫爸爸时他正在拍照。"], perfectZh: "爸爸已经拍了很多照片。" },
  teach: { present: ["Mrs Green teaches us English.", "格林老师教我们英语。"], pastZh: "格林老师去年教我们英语。", continuous: ["She was teaching when the fire alarm rang.", "火警响时她正在上课。"], perfectZh: "她从2020年起就在这里教学。" },
  tell: { present: ["Dad tells us a story every night.", "爸爸每天晚上给我们讲故事。"], pastZh: "他给我讲了一个有趣的故事。", continuous: ["He was telling a story when Mum came in.", "妈妈进来时他正在讲故事。"], perfectZh: "我已经告诉你真相了。" },
  think: { present: ["I think this book is interesting.", "我认为这本书很有趣。"], pastZh: "我认为考试很容易。", continuous: ["I was thinking about your idea on the bus.", "我在公交车上一直在考虑你的想法。"], perfectZh: "你考虑过我的想法吗？", continuousNote: "think 表示“认为”时通常不用进行时；表示“思考、考虑”时可以使用。" },
  throw: { present: ["We throw the ball to each other in the park.", "我们在公园里互相扔球。"], pastZh: "本把球扔给了我。", continuous: ["Ben was throwing the ball when he fell.", "本摔倒时正在扔球。"], perfectZh: "有人已经把我的笔记扔掉了。" },
  understand: { present: ["I understand this question now.", "我现在理解这个问题了。"], pastZh: "我终于理解了这个问题。", continuousNote: "understand 表示理解的状态，通常不使用进行时。", perfectZh: "她一直都理解我。" },
  wake: { present: ["I wake at six every morning.", "我每天早上六点醒来。"], pastZh: "我今天早上六点醒了。", continuous: ["I was waking up when the alarm stopped.", "闹钟停止时我正在醒来。"], perfectZh: "噪音已经吵醒了宝宝。" },
  wear: { present: ["I wear a uniform to school every day.", "我每天穿校服上学。"], pastZh: "她昨天穿了一件红色外套。", continuous: ["She was wearing a red coat when I saw her.", "我看见她时她正穿着红色外套。"], perfectZh: "我从未戴过眼镜。" },
  win: { present: ["Our team often wins at home.", "我们队在主场经常获胜。"], pastZh: "我们队赢得了决赛。", continuous: ["Our team was winning when the rain started.", "开始下雨时我们队正处于领先。"], perfectZh: "米娅已经赢得了三个奖项。" },
  write: { present: ["I write emails every day.", "我每天写电子邮件。"], pastZh: "我昨天写了一张明信片。", continuous: ["I was writing an email when Mum called.", "妈妈打电话时我正在写电子邮件。"], perfectZh: "她今天已经写了三封电子邮件。" },
  play: { present: ["We play football after school.", "我们放学后踢足球。"], pastZh: "我们放学后踢了足球。", continuous: ["We were playing football when it rained.", "下雨时我们正在踢足球。"], perfectZh: "我以前玩过这个游戏。" },
  watch: { present: ["We watch a film every Friday.", "我们每周五看一部电影。"], pastZh: "他们昨晚看了一部电影。", continuous: ["We were watching a film when Dad came home.", "爸爸回家时我们正在看电影。"], perfectZh: "我们已经看过那个视频了。" },
  live: { present: ["I live near my school.", "我住在学校附近。"], pastZh: "我小时候住在约克。", continuous: ["We were living in York when I started school.", "我开始上学时我们正住在约克。"], perfectZh: "她已经在这里住了两年。" },
  study: { present: ["I study English every day.", "我每天学习英语。"], pastZh: "他昨天为考试复习了。", continuous: ["I was studying when my friend called.", "朋友打电话时我正在学习。"], perfectZh: "我们从2022年起就一直学习英语。" },
  stop: { present: ["The bus stops near our house every morning.", "公交车每天早上停在我家附近。"], pastZh: "公交车停在了我家附近。", continuous: ["The bus was stopping when I stood up.", "我站起来时公交车正在停车。"], perfectZh: "雨终于停了。" },
  visit: { present: ["We visit Grandma every Sunday.", "我们每周日去看望奶奶。"], pastZh: "我们星期六参观了城堡。", continuous: ["We were visiting the castle when it began to rain.", "开始下雨时我们正在参观城堡。"], perfectZh: "我去过巴黎两次。" },
}
