CREATE TABLE IF NOT EXISTS esc_synonym_point (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(180) NOT NULL,
  mode VARCHAR(16) NOT NULL COMMENT 'synonym/antonym',
  level_code VARCHAR(32) NOT NULL DEFAULT 'ket',
  source VARCHAR(64) NOT NULL DEFAULT '',
  section_name VARCHAR(128) NOT NULL DEFAULT '',
  left_text VARCHAR(1000) NOT NULL,
  left_cn VARCHAR(1000) DEFAULT '',
  right_text VARCHAR(1000) NOT NULL,
  right_cn VARCHAR(1000) DEFAULT '',
  sort INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1 COMMENT '0 draft, 1 published, 2 disabled',
  tenant_id BIGINT NOT NULL DEFAULT 0,
  creator VARCHAR(64) DEFAULT '', create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater VARCHAR(64) DEFAULT '', update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted BIT(1) NOT NULL DEFAULT 0,
  UNIQUE KEY uk_synonym_point_code (tenant_id, code, deleted),
  INDEX idx_synonym_point_pool (level_code, mode, status, sort)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Synonym and antonym knowledge points';

CREATE TABLE IF NOT EXISTS esc_user_synonym_progress (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  point_id BIGINT NOT NULL,
  seen_count INT NOT NULL DEFAULT 0,
  correct_count INT NOT NULL DEFAULT 0,
  wrong_count INT NOT NULL DEFAULT 0,
  mastered BIT(1) NOT NULL DEFAULT 0,
  last_answered_at DATETIME DEFAULT NULL,
  tenant_id BIGINT NOT NULL DEFAULT 0,
  creator VARCHAR(64) DEFAULT '', create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater VARCHAR(64) DEFAULT '', update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted BIT(1) NOT NULL DEFAULT 0,
  UNIQUE KEY uk_user_synonym_progress (tenant_id, user_id, point_id, deleted),
  INDEX idx_user_synonym_progress_user (user_id, mastered, last_answered_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='User synonym practice progress';

CREATE TABLE IF NOT EXISTS esc_synonym_attempt (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  point_id BIGINT NOT NULL,
  answer_text VARCHAR(1000) NOT NULL,
  correct BIT(1) NOT NULL,
  duration_seconds INT DEFAULT NULL,
  tenant_id BIGINT NOT NULL DEFAULT 0,
  creator VARCHAR(64) DEFAULT '', create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater VARCHAR(64) DEFAULT '', update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted BIT(1) NOT NULL DEFAULT 0,
  INDEX idx_synonym_attempt_user (user_id, point_id, create_time),
  INDEX idx_synonym_attempt_point (point_id, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Synonym practice attempts';

INSERT INTO system_menu
  (name, permission, type, sort, parent_id, path, icon, component, status, visible, keep_alive, always_show)
SELECT '同义替换题库', '', 2, 44, 5047, 'synonym', '#', 'english/synonym/index', 0, b'1', b'1', b'1'
WHERE NOT EXISTS (SELECT 1 FROM system_menu WHERE parent_id = 5047 AND path = 'synonym' AND deleted = b'0');
SET @synonym_menu_id := (SELECT id FROM system_menu WHERE parent_id = 5047 AND path = 'synonym' AND deleted = b'0' ORDER BY id LIMIT 1);
INSERT INTO system_menu
  (name, permission, type, sort, parent_id, path, icon, component, status, visible, keep_alive, always_show)
SELECT p.name, p.permission, 3, p.sort, @synonym_menu_id, '', '#', NULL, 0, b'1', b'1', b'1'
FROM (
  SELECT '同义替换查询' name, 'english:synonym:query' permission, 1 sort
  UNION ALL SELECT '同义替换创建', 'english:synonym:create', 2
  UNION ALL SELECT '同义替换更新', 'english:synonym:update', 3
  UNION ALL SELECT '同义替换删除', 'english:synonym:delete', 4
) p WHERE NOT EXISTS (SELECT 1 FROM system_menu m WHERE m.permission = p.permission AND m.deleted = b'0');

-- Generated from local synonym books. Re-run extract_synonym_bank.py after source book changes.
INSERT INTO esc_synonym_point
  (code, mode, level_code, source, section_name, left_text, left_cn, right_text, right_cn, sort, status, tenant_id)
VALUES
  ('ket-trainer-test1-reading-part1-009-synonym-on-foot-walk-980cb4a9', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part1', 'on foot', '走路', 'walk', '走路', 1, 1, 1),
  ('ket-trainer-test1-reading-part1-011-synonym-pupil-student-145e49c3', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part1', 'Pupil', '小学生', 'student', '学生', 2, 1, 1),
  ('ket-trainer-test1-reading-part1-013-synonym-by-car-drive-86ff7d09', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part1', 'By car', '坐小汽车', 'drive', '开车', 3, 1, 1),
  ('ket-trainer-test1-reading-part1-015-synonym-forest-wood-a4287a42', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part1', 'Forest', '森林', 'wood', '树林', 4, 1, 1),
  ('ket-trainer-test1-reading-part1-017-synonym-summer-warmer-96a0c82e', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part1', 'Summer', '夏天', 'warmer', '更暖和', 5, 1, 1),
  ('ket-trainer-test1-reading-part1-019-synonym-under-8s-only-children-da26d8bc', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part1', 'Under 8s only', '只能低于 8 岁的人', 'children', '孩子', 6, 1, 1),
  ('ket-trainer-test1-reading-part1-021-synonym-for-13-19-year-olds-teenagers-acaa2439', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part1', 'For 13-19 year-olds', '给 13-19 岁的人', 'teenagers', '青少年', 7, 1, 1),
  ('ket-trainer-test1-reading-part1-023-synonym-for-20-35-year-olds-adults-357b912a', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part1', 'For 20-35 year-olds', '给 20-35 岁的人', 'adults', '成年人', 8, 1, 1),
  ('ket-trainer-test1-reading-part1-025-synonym-no-one-over-12-children-d75aaceb', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part1', 'No one over 12', '不能超过 12 岁', 'children', '孩子', 9, 1, 1),
  ('ket-trainer-test1-reading-part1-027-synonym-this-afternoons-football-class-will-be-tomorrow-instead-theres-no-football-class-today-25fac1dc', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part1', 'This afternoon’s football class will be tomorrow instead', '今天下午的 足球课改到明天', 'There’s no football class today', '今天没有足球课', 10, 1, 1),
  ('ket-trainer-test1-reading-part1-031-synonym-picnic-area-a-place-for-eating-e13e6ed8', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part1', 'Picnic area', '野餐区域', 'a place for eating', '吃饭的地方', 11, 1, 1),
  ('ket-trainer-test1-reading-part1-033-synonym-no-ball-games-here-you-cant-play-football-here-67589882', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part1', 'No ball games here', '这里禁止玩球类运动', 'you can’t play football here', '你不能在这里踢 足球', 12, 1, 1),
  ('ket-trainer-test1-reading-part1-037-synonym-buy-two-at-the-same-time-third-one-is-free-three-costs-the-same-as-two-2bf21644', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part1', 'Buy two at the same time,third one is free', '同时买两个，第三个免费', 'three costs the same as two', '三个和两个的价格一样', 13, 1, 1),
  ('ket-trainer-test1-reading-part2-043-synonym-open-every-day-except-sunday-closed-on-sundays-e74b7bf4', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part2', 'Open every day except Sunday', '除了周天，每天都开', 'closed on Sundays', '周天关门', 14, 1, 1),
  ('ket-trainer-test1-reading-part2-045-synonym-tea-drinks-7b9d715e', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part2', 'tea', '茶，coffee 咖啡', 'drinks', '饮料', 15, 1, 1),
  ('ket-trainer-test1-reading-part2-047-synonym-cakes-snacks-d73f7a13', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part2', 'Cakes', '蛋糕，biscuits 饼干', 'snacks', '零食，小吃', 16, 1, 1),
  ('ket-trainer-test1-reading-part2-049-synonym-summer-warmer-63002b8a', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part2', 'Summer', '夏天', 'warmer', '更暖和', 17, 1, 1),
  ('ket-trainer-test1-reading-part2-051-synonym-uniform-clothes-b425f76a', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part2', 'Uniform', '校服', 'clothes', '衣服', 18, 1, 1),
  ('ket-trainer-test1-reading-part2-053-synonym-can-touch-can-pick-up-any-objects-cdd4e149', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part2', 'Can touch', '可以摸', 'can pick up any objects', '可以拿起任何物品', 19, 1, 1),
  ('ket-trainer-test1-reading-part2-055-synonym-how-people-travel-vehicle-67ff46e9', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part2', 'How people travel', '人们如何出行', 'vehicle', '交通工具', 20, 1, 1),
  ('ket-trainer-test1-reading-part2-057-synonym-many-years-ago-in-the-past-1bdd236f', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part2', 'Many years ago', '很多年以前', 'in the past', '在以前', 21, 1, 1),
  ('ket-trainer-test1-reading-part2-059-synonym-lent-by-other-museum-borrowed-from-other-museum-5bfd3348', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part2', 'Lent by other museum', '由其他博物馆借出的', 'borrowed from other museum', '从其他博 物馆借来的', 22, 1, 1),
  ('ket-trainer-test1-reading-part2-063-synonym-wooden-cinema-seating-furniture-d5ed31a3', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part2', 'Wooden cinema seating', '电影院的木座椅', 'furniture', '家具', 23, 1, 1),
  ('ket-trainer-test1-reading-part3-067-synonym-couldnt-believe-surprised-ef73c130', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part3', 'couldn''t believe', '无法相信', 'surprised', '惊讶的', 24, 1, 1),
  ('ket-trainer-test1-reading-part3-069-synonym-havent-change-look-the-same-55f30405', 'synonym', 'ket', 'KET Trainer', 'Test1 Reading Part3', 'haven’t change', '没有变化', 'look the same', '看起来一样', 25, 1, 1),
  ('ket-trainer-test1-listening-part2-073-synonym-start-begin-9671e214', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part2', 'start', '开始', 'begin', '开始', 26, 1, 1),
  ('ket-trainer-test1-listening-part2-075-synonym-end-finish-c214a342', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part2', 'End', '结束', 'finish', '结束', 27, 1, 1),
  ('ket-trainer-test1-listening-part2-077-synonym-start-at-4-20-end-at-5-from-4-20-to-5-00-609c2ce7', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part2', 'Start at 4:20 end at 5', '', 'from 4:20 to 5:00', '', 28, 1, 1),
  ('ket-trainer-test1-listening-part3-081-synonym-isnt-easy-hard-b4bc780f', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part3', 'Isn’t easy', '不容易', 'hard', '困难的', 29, 1, 1),
  ('ket-trainer-test1-listening-part3-083-synonym-sick-not-well-a25ddff0', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part3', 'Sick', '生病的', 'not well', '不好', 30, 1, 1),
  ('ket-trainer-test1-listening-part3-085-synonym-fast-not-slow-3811531d', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part3', 'Fast', '快的', 'not slow', '不慢', 31, 1, 1),
  ('ket-trainer-test1-listening-part3-087-synonym-bad-not-good-d6bf1c95', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part3', 'Bad', '坏的，糟糕的', 'not good', '不好的', 32, 1, 1),
  ('ket-trainer-test1-listening-part3-089-synonym-hard-not-soft-2dbf8938', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part3', 'Hard', '硬的', 'not soft', '不软的', 33, 1, 1),
  ('ket-trainer-test1-listening-part3-091-synonym-three-quarters-of-an-hour-forty-five-minutes45-98afd827', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part3', 'Three quarters of an hour', '一个小时的四分之三', 'forty-five minutes45', '分钟', 34, 1, 1),
  ('ket-trainer-test1-listening-part3-093-synonym-like-best-enjoy-most-e80b400c', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part3', 'Like best', '最喜欢的', 'enjoy most', '最享受的', 35, 1, 1),
  ('ket-trainer-test1-listening-part4-097-synonym-something-to-eat-food-425415f2', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part4', 'Something to eat', '吃的东西', 'food', '食物', 36, 1, 1),
  ('ket-trainer-test1-listening-part4-099-synonym-something-to-wear-gloves-f02f127e', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part4', 'Something to wear', '穿的东西', 'gloves', '手套', 37, 1, 1),
  ('ket-trainer-test1-listening-part4-101-synonym-flight-was-cancelled-arrive-back-late-f011d3ab', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part4', 'Flight was cancelled', '航班被取消', 'arrive back late', '到达晚了', 38, 1, 1),
  ('ket-trainer-test1-listening-part4-103-synonym-lesson-course-66256513', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part4', 'Lesson', '课程', 'course', '课程', 39, 1, 1),
  ('ket-trainer-test1-listening-part4-105-synonym-the-most-interesting-like-best-f6285fbb', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part4', 'The most interesting', '最有趣的', 'like best', '最爱的', 40, 1, 1),
  ('ket-trainer-test1-listening-part4-107-synonym-lesson-about-bees-biology-762a9de3', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part4', 'Lesson about bees', '关于蜜蜂的课程', 'biology', '生物课', 41, 1, 1),
  ('ket-trainer-test1-listening-part4-109-synonym-turn-down-the-heating-the-room-is-hot-716437b2', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part4', 'Turn down the heating', '调低供热系统', 'the room is hot', '房间很热', 42, 1, 1),
  ('ket-trainer-test1-listening-part5-113-synonym-grow-food-farmer-d6015068', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part5', 'Grow food', '种植食物', 'farmer', '农民', 43, 1, 1),
  ('ket-trainer-test1-listening-part5-115-synonym-writes-for-newspaper-journalist-e54f7894', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part5', 'Writes for newspaper', '给报纸写文章', 'journalist', '记者', 44, 1, 1),
  ('ket-trainer-test1-listening-part5-117-synonym-looks-after-sick-people-nurse-b133619e', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part5', 'Looks after sick people', '照顾病人', 'nurse', '护士', 45, 1, 1),
  ('ket-trainer-test1-listening-part5-119-synonym-tells-people-what-to-do-at-work-manager-e463fbd3', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part5', 'Tells people what to do at work', '告诉人们在工作中怎么做', 'manager', '经理', 46, 1, 1),
  ('ket-trainer-test1-listening-part5-121-synonym-repairs-cars-mechanic-d7296937', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part5', 'Repairs cars', '修理汽车', 'mechanic', '机械师', 47, 1, 1),
  ('ket-trainer-test1-listening-part5-123-synonym-looks-after-peoples-teeth-dentist-a2c5fdde', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part5', 'Looks after people’s teeth', '照顾人们的牙齿', 'dentist', '牙医', 48, 1, 1),
  ('ket-trainer-test1-listening-part5-125-synonym-builds-or-looks-after-machines-engineer-1b3c6e0c', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part5', 'Builds or looks after machines', '建造或者照看机器', 'engineer', '工程师 50 Meets people when they first come to the office 当人们第一次来办公室带他们见人=receptionist 接待员', 49, 1, 1),
  ('ket-trainer-test1-listening-part5-131-synonym-fly-planes-pilot-6687c42c', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part5', 'Fly planes', '开飞机', 'pilot', '飞行员', 50, 1, 1),
  ('ket-trainer-test1-listening-part5-133-synonym-take-care-of-peoples-teeth-dentist-2bb2a05e', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part5', 'Take care of people’s teeth', '照顾人们的牙齿', 'dentist', '牙医', 51, 1, 1),
  ('ket-trainer-test1-listening-part5-135-synonym-show-tourists-round-tour-guide-418514dc', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part5', 'Show tourists round', '带游客逛', 'tour guide', '导游', 52, 1, 1),
  ('ket-trainer-test1-listening-part5-137-synonym-writes-articles-for-newspaper-journalist-50be1df4', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part5', 'Writes articles for newspaper', '给报纸写文章', 'journalist', '记者', 53, 1, 1),
  ('ket-trainer-test1-listening-part5-139-synonym-be-in-play-actor-03356c62', 'synonym', 'ket', 'KET Trainer', 'Test1 Listening Part5', 'Be in play', '在剧里，work in theatre 在剧院工作', 'actor', '演员', 54, 1, 1),
  ('ket-trainer-test2-reading-part1-145-synonym-collect-pick-up-cff609dd', 'synonym', 'ket', 'KET Trainer', 'Test2 Reading Part1', 'Collect', '领取', 'pick up', '获得', 55, 1, 1),
  ('ket-trainer-test2-reading-part1-147-synonym-dont-enter-the-pool-before-you-use-the-shower-need-to-wash-before-you-swim-8bcbba61', 'synonym', 'ket', 'KET Trainer', 'Test2 Reading Part1', 'Don’t enter the pool before you use the shower', '洗澡之前不能进泳池', 'need to wash before you swim', '游泳之前要洗', 56, 1, 1),
  ('ket-trainer-test2-reading-part1-151-synonym-photo-picture-14ba6606', 'synonym', 'ket', 'KET Trainer', 'Test2 Reading Part1', 'Photo', '图片', 'picture', '照片', 57, 1, 1),
  ('ket-trainer-test2-reading-part1-153-synonym-buy-tickets-to-4-films-and-you-dont-need-to-pay-for-the-next-one-the-fifth-film-you-see-is-free-16081cae', 'synonym', 'ket', 'KET Trainer', 'Test2 Reading Part1', 'Buy tickets to 4 films and you don’t need to pay for the next one', '买 4 部电影票,下一部就不 用付钱', 'the fifth film you see is free', '你看的第 5 部电影是免费的', 58, 1, 1),
  ('ket-trainer-test2-reading-part2-159-antonym-worst-best-1717097f', 'antonym', 'ket', 'KET Trainer', 'Test2 Reading part2', 'worst', '最坏的', 'best', '最好的', 59, 1, 1),
  ('ket-trainer-test2-reading-part2-161-antonym-everything-nothing-930c120e', 'antonym', 'ket', 'KET Trainer', 'Test2 Reading part2', 'everything', '所有事情', 'nothing', '没有事情', 60, 1, 1),
  ('ket-trainer-test2-reading-part2-163-antonym-small-large-ad4cd19a', 'antonym', 'ket', 'KET Trainer', 'Test2 Reading part2', 'small', '小的', 'large', '大的', 61, 1, 1),
  ('ket-trainer-test2-reading-part2-165-antonym-leave-enter-55f0a553', 'antonym', 'ket', 'KET Trainer', 'Test2 Reading part2', 'leave', '离开', 'enter', '进入', 62, 1, 1),
  ('ket-trainer-test2-reading-part2-167-antonym-after-before-7595ba37', 'antonym', 'ket', 'KET Trainer', 'Test2 Reading part2', 'after', '在...之后', 'before', '在...之前', 63, 1, 1),
  ('ket-trainer-test2-reading-part2-169-antonym-finish-start-71e35606', 'antonym', 'ket', 'KET Trainer', 'Test2 Reading part2', 'finish', '结束', 'start', '开始', 64, 1, 1),
  ('ket-trainer-test2-reading-part2-171-antonym-light-heavy-ae2d7aa6', 'antonym', 'ket', 'KET Trainer', 'Test2 Reading part2', 'light', '轻的', 'heavy', '重的', 65, 1, 1),
  ('ket-trainer-test2-reading-part2-175-antonym-different-same-2eb6ca99', 'antonym', 'ket', 'KET Trainer', 'Test2 Reading part2', 'different', '不同的', 'same', '相同的', 66, 1, 1),
  ('ket-trainer-test2-reading-part2-177-antonym-hate-love-4ea9b67a', 'antonym', 'ket', 'KET Trainer', 'Test2 Reading part2', 'hate', '讨厌', 'love', '爱', 67, 1, 1),
  ('ket-trainer-test2-reading-part2-179-antonym-never-always-8e2aed36', 'antonym', 'ket', 'KET Trainer', 'Test2 Reading part2', 'never', '从不', 'always', '总是', 68, 1, 1),
  ('ket-trainer-test2-reading-part2-181-antonym-together-enjoy-myself-doing-it-7be5ba5c', 'antonym', 'ket', 'KET Trainer', 'Test2 Reading part2', 'together', '一起-alone 独自的 Fun 有趣的', 'enjoy myself doing it', '享受做它', 69, 1, 1),
  ('ket-trainer-test2-reading-part2-185-synonym-every-day-always-fec40997', 'synonym', 'ket', 'KET Trainer', 'Test2 Reading part2', 'Every day', '每天', 'always', '总是', 70, 1, 1),
  ('ket-trainer-test2-reading-part2-187-synonym-every-day-expect-sunday-usually-0b410fdc', 'synonym', 'ket', 'KET Trainer', 'Test2 Reading part2', 'Every day expect sunday', '除了周天每天都做', 'usually', '通常', 71, 1, 1),
  ('ket-trainer-test2-reading-part2-189-synonym-once-a-month-sometimes-350917e3', 'synonym', 'ket', 'KET Trainer', 'Test2 Reading part2', 'Once a month', '一个月一次', 'sometimes', '偶尔', 72, 1, 1),
  ('ket-trainer-test2-reading-part2-191-synonym-doesnt-do-never-6db6f487', 'synonym', 'ket', 'KET Trainer', 'Test2 Reading part2', 'Doesn’t do', '不做', 'never', '从不', 73, 1, 1),
  ('ket-trainer-test2-reading-part2-193-synonym-play-some-jazz-listen-to-music-4c7463ef', 'synonym', 'ket', 'KET Trainer', 'Test2 Reading part2', 'Play some jazz', '放爵士乐', 'listen to music', '听音乐', 74, 1, 1),
  ('ket-trainer-test2-reading-part2-195-synonym-classsmate-friend-e865d01b', 'synonym', 'ket', 'KET Trainer', 'Test2 Reading part2', 'Classsmate', '同学', 'friend', '朋友', 75, 1, 1),
  ('ket-trainer-test2-reading-part2-197-synonym-let-my-parents-and-sister-know-tell-my-family-a2448d78', 'synonym', 'ket', 'KET Trainer', 'Test2 Reading part2', 'Let my parents and sister know', '让我父母和妹妹知道', 'tell my family', '告诉我的家人', 76, 1, 1),
  ('ket-trainer-test2-reading-part2-199-synonym-turn-my-mobile-off-not-to-look-at-my-phone-337655f4', 'synonym', 'ket', 'KET Trainer', 'Test2 Reading part2', 'Turn my mobile off', '关掉手机', 'not to look at my phone', '不看手机', 77, 1, 1),
  ('ket-trainer-test2-reading-part2-201-synonym-before-i-go-to-bed-in-the-evening-bfdeef7d', 'synonym', 'ket', 'KET Trainer', 'Test2 Reading part2', 'Before I go to bed', '上床前', 'in the evening', '在晚上', 78, 1, 1),
  ('ket-trainer-test2-reading-part2-203-synonym-wake-up-in-the-morning-7e759b7f', 'synonym', 'ket', 'KET Trainer', 'Test2 Reading part2', 'wake up', '醒来', 'in the morning', '在早上', 79, 1, 1),
  ('ket-trainer-test2-reading-part2-205-synonym-enough-light-bright-204dd08b', 'synonym', 'ket', 'KET Trainer', 'Test2 Reading part2', 'Enough light', '足够的光', 'bright', '明亮的', 80, 1, 1),
  ('ket-trainer-test2-reading-part2-207-synonym-these-days-now-1c2d4a6c', 'synonym', 'ket', 'KET Trainer', 'Test2 Reading part2', 'These days', '如今', 'now', '现在', 81, 1, 1),
  ('ket-trainer-test2-reading-part3-211-synonym-i-like-it-its-brilliant-bec6fe88', 'synonym', 'ket', 'KET Trainer', 'Test2 Reading part3', 'I like it', '我喜欢它', 'It’s brilliant', '它很出色=I enjoy doing...我享受做...=I’m a fan of...我是', 82, 1, 1),
  ('ket-trainer-test2-reading-part3-215-synonym-i-dont-like-it-its-awful-7d7da980', 'synonym', 'ket', 'KET Trainer', 'Test2 Reading part3', 'I don’t like it', '我不喜欢它', 'It’s awful', '它很糟糕=I’m angry about it 我对它很生气=It’s', 83, 1, 1),
  ('ket-trainer-test2-reading-part3-217-synonym-boring-its-horrible-36708f02', 'synonym', 'ket', 'KET Trainer', 'Test2 Reading part3', 'boring', '它很无聊', 'It’s horrible', '它很可怕=It’s terrible 它很可怕=It’s the worst 它是最差 （糟糕）的', 84, 1, 1),
  ('ket-trainer-test2-reading-part3-221-synonym-think-about-what-was-wrong-and-decided-how-to-do-better-next-time-learn-from-mistakes-4cbbd7fd', 'synonym', 'ket', 'KET Trainer', 'Test2 Reading part3', 'Think about what was wrong and decided how to do better next time', '思考哪里有问题然 后决定下次怎样做的更好', 'learn from mistakes', '从错误中学习', 85, 1, 1),
  ('ket-trainer-test2-reading-part3-225-synonym-amazing-good-8b1b6958', 'synonym', 'ket', 'KET Trainer', 'Test2 Reading part3', 'Amazing', '令人惊讶的，了不起的', 'good', '好的', 86, 1, 1),
  ('ket-trainer-test2-reading-part3-227-synonym-i-dont-think-theres-anyone-who-cant-take-amazing-photos-everybody-can-take-good-photos-4819e3c2', 'synonym', 'ket', 'KET Trainer', 'Test2 Reading part3', 'I don’t think there’s anyone who can’t take amazing photos', '我认为没有人会拍不出好照 片', 'everybody can take good photos', '所有人都能拍好照片', 87, 1, 1),
  ('ket-trainer-test2-reading-part3-231-synonym-didnt-goto-the-party-missed-the-party-0fb8b306', 'synonym', 'ket', 'KET Trainer', 'Test2 Reading part3', 'Didn’t goto the party', '没去派对', 'missed the party', '错过派对', 88, 1, 1),
  ('ket-trainer-test2-listening-part2-237-synonym-wild-animals-bear-df6c6af3', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part2', 'Wild animals', '野生动物', 'bear', '熊，camel 骆驼，elephant 大象，lion 狮子，tiger 老虎', 89, 1, 1),
  ('ket-trainer-test2-listening-part2-239-synonym-pets-cat-395c7305', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part2', 'Pets', '宠物', 'cat', '猫，fish 鱼，dog 狗，rabbit 兔子', 90, 1, 1),
  ('ket-trainer-test2-listening-part2-241-synonym-farm-animals-sheep-8a963b52', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part2', 'Farm animals', '农场动物', 'sheep', '羊，chicken 鸡，cow 奶牛，horse 马', 91, 1, 1),
  ('ket-trainer-test2-listening-part2-243-synonym-give-you-a-present-free-1996dbdd', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part2', 'Give you a present', '给你个礼物', 'free', '免费的', 92, 1, 1),
  ('ket-trainer-test2-listening-part2-245-synonym-worry-about-it-afraid-f0dcfd8c', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part2', 'Worry about it', '担心它', 'afraid', '害怕的', 93, 1, 1),
  ('ket-trainer-test2-listening-part3-249-synonym-its-a-pity-they-didnt-have-anywhere-to-buy-food-need-a-shop-f80a4718', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part3', 'It’s a pity they didn’t have anywhere to buy food', '很可惜没有地方可以买食物', 'need a shop', '需要一个商店', 94, 1, 1),
  ('ket-trainer-test2-listening-part3-253-synonym-amazing-like-best-0fcbe5dc', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part3', 'Amazing', '非常棒', 'like best', '最爱', 95, 1, 1),
  ('ket-trainer-test2-listening-part4-257-synonym-auntie-a-member-of-the-family-0b67351d', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part4', 'Auntie', '姑姑，姨', 'a member of the family', '家庭成员', 96, 1, 1),
  ('ket-trainer-test2-listening-part4-259-synonym-online-on-the-internet-8d7606fb', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part4', 'Online', '网上', 'on the internet', '在网上', 97, 1, 1),
  ('ket-trainer-test2-listening-part4-261-synonym-notice-poster-16149c48', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part4', 'notice', '通知', 'poster', '海报', 98, 1, 1),
  ('ket-trainer-test2-listening-part4-263-synonym-my-uncle-they-know-the-person-fa758b19', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part4', 'My uncle', '我的叔叔', 'they know the person', '他们认识这个人', 99, 1, 1),
  ('ket-trainer-test2-listening-part4-265-synonym-people-who-works-in-the-school-office-school-secretary-4a1d2837', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part4', 'People who works in the school office', '在学校办公室工作的人', 'school secretary', '校秘书', 100, 1, 1),
  ('ket-trainer-test2-listening-part5-269-synonym-play-the-piano-keyboard-37d7d99e', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part5', 'Play the piano', '弹钢琴', 'keyboard', '键盘=music 音乐', 101, 1, 1),
  ('ket-trainer-test2-listening-part5-271-synonym-sailing-lake-06c14f96', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part5', 'Sailing', '帆船运动', 'lake', '湖=sea 海', 102, 1, 1),
  ('ket-trainer-test2-listening-part5-273-synonym-painting-colours-577d7d93', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part5', 'Painting', '画画', 'colours', '颜色=brush 画笔', 103, 1, 1),
  ('ket-trainer-test2-listening-part5-275-synonym-cook-kitchen-9447e1c6', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part5', 'Cook', '做饭', 'kitchen', '厨房=bake 烘焙=chef 厨师', 104, 1, 1),
  ('ket-trainer-test2-listening-part5-277-synonym-has-been-to-italy-france-spain-visited-different-countries-0e2ecb30', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part5', 'Has been to Italy,France,Spain', '去过意大利，法国，西班牙', 'visited different countries', '去 过不同的国家', 105, 1, 1),
  ('ket-trainer-test2-listening-part5-281-synonym-movies-that-make-you-laugh-funny-films-07f1e4cf', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part5', 'Movies that make you laugh', '让你发笑的电影', 'funny films', '搞笑电影', 106, 1, 1),
  ('ket-trainer-test2-listening-part5-283-synonym-his-cakes-are-amazing-hes-good-at-baking-db6f0f34', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part5', 'His cakes are amazing', '他的蛋糕很棒', 'He’s good at baking', '他擅长烘焙', 107, 1, 1),
  ('ket-trainer-test2-listening-part5-285-synonym-is-in-a-rock-group-plays-in-a-band-ee63c8c3', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part5', 'Is in a rock group', '在一个摇滚组合里', 'plays in a band', '在乐队里演奏', 108, 1, 1),
  ('ket-trainer-test2-listening-part5-287-synonym-enjoys-photography-takes-lots-of-pictures-21177051', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part5', 'Enjoys photography', '享受摄影', 'takes lots of pictures', '拍很多照片', 109, 1, 1),
  ('ket-trainer-test2-listening-part5-289-synonym-interested-in-horror-films-hobby-is-wathing-films-76559b73', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part5', 'Interested in horror films', '对恐怖电影感兴趣', 'hobby is wathing films', '爱好是看电影', 110, 1, 1),
  ('ket-trainer-test2-listening-part5-291-synonym-plays-guitar-in-a-rock-group-in-a-band-1220a474', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part5', 'Plays guitar in a rock group', '在一个摇滚组合里弹吉他', 'in a band', '在一个乐队里', 111, 1, 1),
  ('ket-trainer-test2-listening-part5-293-synonym-studying-spanish-learning-languages-2aa6dbe2', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part5', 'Studying Spanish', '学西班牙语', 'learning languages', '学语言', 112, 1, 1),
  ('ket-trainer-test2-listening-part5-295-synonym-in-a-play-acting-c101d989', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part5', 'In a play', '在一部剧里', 'acting', '演戏', 113, 1, 1),
  ('ket-trainer-test2-listening-part5-297-synonym-exhibition-of-her-pictures-her-hobby-is-photography-fb288845', 'synonym', 'ket', 'KET Trainer', 'Test2 Listening part5', 'Exhibition of her pictures', '她照片的展览', 'her hobby is photography', '她的爱好是摄影', 114, 1, 1),
  ('ket-trainer-test3-reading-part1-303-synonym-its-on-thursday-not-on-wednesday-change-of-plan-3cf5afc2', 'synonym', 'ket', 'KET Trainer', 'Test3 Reading Part1', 'It’s on Thursday,not on Wednesday', '在星期四，不是星期三', 'change of plan', '计划有变', 115, 1, 1),
  ('ket-trainer-test3-reading-part1-305-synonym-hear-listen-dda8a498', 'synonym', 'ket', 'KET Trainer', 'Test3 Reading Part1', 'Hear', '听', 'listen', '听', 116, 1, 1),
  ('ket-trainer-test3-reading-part1-307-synonym-tickets-are-available-you-can-now-buy-tickets-66a980ba', 'synonym', 'ket', 'KET Trainer', 'Test3 Reading Part1', 'Tickets are available', '有票', 'you can now buy tickets', '你可以现在买票', 117, 1, 1),
  ('ket-trainer-test3-reading-part1-309-synonym-left-lost-b591e758', 'synonym', 'ket', 'KET Trainer', 'Test3 Reading Part1', 'Left', '遗留', 'lost', '丢失', 118, 1, 1),
  ('ket-trainer-test3-reading-part1-311-synonym-can-i-use-yours-borrow-something-ae8de35c', 'synonym', 'ket', 'KET Trainer', 'Test3 Reading Part1', 'Can I use yours', '我可以用你的吗？', 'borrow something', '借东西', 119, 1, 1),
  ('ket-trainer-test3-reading-part2-315-synonym-appears-on-tv-talk-about-matches-work-as-a-journalist-65a093da', 'synonym', 'ket', 'KET Trainer', 'Test3 Reading Part2', 'Appears on TV,talk about matches', '出现在电视上谈论比赛', 'work as a journalist', '当记者', 120, 1, 1),
  ('ket-trainer-test3-reading-part2-317-synonym-help-large-numbers-of-people-become-interested-in-make-more-popular-ff53639a', 'synonym', 'ket', 'KET Trainer', 'Test3 Reading Part2', 'Help large numbers of people become interested in', '帮助大量的人变得对...感兴趣', 'make... more popular', '使得...更流行', 121, 1, 1),
  ('ket-trainer-test3-reading-part2-321-synonym-the-only-under-14-year-old-the-youngest-374b2a3d', 'synonym', 'ket', 'KET Trainer', 'Test3 Reading Part2', 'The only under-14-year-old', '唯一低于 14 岁的', 'the youngest', '最年轻的', 122, 1, 1),
  ('ket-trainer-test3-reading-part2-323-synonym-everyone-thought-nobody-could-do-this-people-believed-its-not-possible-fa091e59', 'synonym', 'ket', 'KET Trainer', 'Test3 Reading Part2', 'Everyone thought nobody could do this', '所有人认为没有人能做到', 'people believed it’s not possible', '人们认为不可能', 123, 1, 1),
  ('ket-trainer-test3-reading-part2-327-synonym-born-in-one-country-live-in-another-from-nepal-these-days-is-in-the-uk-e98c2bcc', 'synonym', 'ket', 'KET Trainer', 'Test3 Reading Part2', 'Born in one country,live in another', '出生在一个国家，住在另一个国家', 'from Nepal，these days is in the UK', '来自尼泊尔，现在在英国', 124, 1, 1),
  ('ket-trainer-test3-reading-part3-333-synonym-open-her-own-company-start-her-own-business-65a75a20', 'synonym', 'ket', 'KET Trainer', 'Test3 Reading Part3', 'Open her own company', '开她自己的公司', 'start her own business', '自己创业', 125, 1, 1),
  ('ket-trainer-test3-reading-part3-335-synonym-help-her-to-think-of-give-her-ideas-820774b7', 'synonym', 'ket', 'KET Trainer', 'Test3 Reading Part3', 'Help her to think of', '帮助她想出', 'give her ideas', '给她主意', 126, 1, 1),
  ('ket-trainer-test3-reading-part3-337-synonym-knows-what-is-needed-to-be-succeed-in-the-world-of-fashion-understands-the-fashion-business-ca92021c', 'synonym', 'ket', 'KET Trainer', 'Test3 Reading Part3', 'Knows what is needed to be succeed in the world of fashion', '知道在时尚界成功需要什么', 'understands the fashion business', '理解时装界', 127, 1, 1),
  ('ket-trainer-test3-listening-part3-343-synonym-the-family-who-live-next-door-to-us-neighbor-82201043', 'synonym', 'ket', 'KET Trainer', 'Test3 Listening Part3', 'The family who live next door to us', '住在我们隔壁的家庭', 'neighbor', '邻居', 128, 1, 1),
  ('ket-trainer-test3-listening-part3-345-synonym-rained-wet-5a5678f0', 'synonym', 'ket', 'KET Trainer', 'Test3 Listening Part3', 'Rained', '下过雨', 'wet', '湿的', 129, 1, 1),
  ('ket-trainer-test3-listening-part3-347-synonym-get-information-about-find-out-about-6dbfd0ce', 'synonym', 'ket', 'KET Trainer', 'Test3 Listening Part3', 'Get information about', '获得关于...的信息', 'find out about', '弄清关于...的情况', 130, 1, 1),
  ('ket-trainer-test3-listening-part3-349-synonym-you-can-see-cars-that-are-over-fifty-years-old-an-exhibitionof-old-cars-78cab563', 'synonym', 'ket', 'KET Trainer', 'Test3 Listening Part3', 'You can see cars that are over fifty years old', '你可以看到超过 50 年的车', 'an exhibitionof old cars', '旧车展览', 131, 1, 1),
  ('ket-trainer-test3-listening-part4-355-synonym-started-beginning-7a0045ec', 'synonym', 'ket', 'KET Trainer', 'Test3 Listening Part4', 'Started', '开始', 'beginning', '开始', 132, 1, 1),
  ('ket-trainer-test3-listening-part4-357-synonym-difficult-didnt-understand-4ee8ec15', 'synonym', 'ket', 'KET Trainer', 'Test3 Listening Part4', 'Difficult', '困难的', 'didn’t understand', '不理解', 133, 1, 1),
  ('ket-trainer-test3-listening-part4-359-synonym-last-part-the-end-fb3624d2', 'synonym', 'ket', 'KET Trainer', 'Test3 Listening Part4', 'Last part', '最后的部分', 'the end', '结尾', 134, 1, 1),
  ('ket-trainer-test3-listening-part4-361-synonym-ive-never-heard-seen-it-is-unusual-53cfc588', 'synonym', 'ket', 'KET Trainer', 'Test3 Listening Part4', 'I’ve never heard/seen', '我从没听过/见过', 'it is unusual', '它不寻常', 135, 1, 1),
  ('ket-trainer-test3-listening-part4-363-synonym-awful-terrible-05038d2c', 'synonym', 'ket', 'KET Trainer', 'Test3 Listening Part4', 'awful', '糟糕的', 'terrible', '糟糕的', 136, 1, 1),
  ('ket-trainer-test3-listening-part4-365-synonym-see-football-match-watch-something-fd7e71ad', 'synonym', 'ket', 'KET Trainer', 'Test3 Listening Part4', 'see football match', '看足球比赛', 'watch something', '看某个东西', 137, 1, 1),
  ('ket-trainer-test3-listening-part4-367-synonym-go-to-a-park-outside-ae1643df', 'synonym', 'ket', 'KET Trainer', 'Test3 Listening Part4', 'Go to a park', '去公园', 'outside', '在户外', 138, 1, 1),
  ('ket-trainer-test3-listening-part4-369-synonym-show-tourist-around-tour-guige-7a1eac50', 'synonym', 'ket', 'KET Trainer', 'Test3 Listening Part4', 'Show tourist around', '带游客逛', 'tour guige', '导游', 139, 1, 1),
  ('ket-trainer-test3-listening-part5-373-synonym-a-long-way-from-far-46a69a69', 'synonym', 'ket', 'KET Trainer', 'Test3 Listening Part5', 'A long way from', '离...有很长一段路', 'far', '远的', 140, 1, 1),
  ('ket-trainer-test3-listening-part5-375-synonym-you-can-hear-the-traffic-in-the-street-noisy-34b57471', 'synonym', 'ket', 'KET Trainer', 'Test3 Listening Part5', 'You can hear the traffic in the street', '你可以听到街道上车辆的声音', 'noisy', '吵的', 141, 1, 1),
  ('ket-trainer-test3-listening-part5-377-synonym-dirty-not-clean-2ec31bbe', 'synonym', 'ket', 'KET Trainer', 'Test3 Listening Part5', 'dirty', '脏的', 'not clean', '不干净', 142, 1, 1),
  ('ket-trainer-test3-listening-part5-379-synonym-not-warm-enough-too-cold-68de54af', 'synonym', 'ket', 'KET Trainer', 'Test3 Listening Part5', 'not warm enough', '不够暖和', 'too cold', '太冷', 143, 1, 1),
  ('ket-trainer-test3-listening-part5-381-synonym-lift-is-so-slow-not-useful-0c34d2ba', 'synonym', 'ket', 'KET Trainer', 'Test3 Listening Part5', 'Lift is so slow', '电梯太慢', 'not useful', '不实用', 144, 1, 1),
  ('ket-trainer-test3-listening-part5-383-synonym-there-wasnt-enough-space-too-small-a6e26023', 'synonym', 'ket', 'KET Trainer', 'Test3 Listening Part5', 'There wasn’t enough space', '没有足够空间', 'too small', '太小', 145, 1, 1),
  ('ket-trainer-test4-reading-part1-389-synonym-buy-two-and-get-the-third-one-half-price-you-can-save-money-65e836f4', 'synonym', 'ket', 'KET Trainer', 'Test4 Reading Part1', 'Buy two and get the third one half price', '买二，第三个就半价', 'you can save money', '你可以 省钱', 146, 1, 1),
  ('ket-trainer-test4-reading-part1-393-synonym-all-staff-and-pupils-anyone-at-the-school-e9dbb378', 'synonym', 'ket', 'KET Trainer', 'Test4 Reading Part1', 'All staff and pupils', '所有的学生和员工', 'anyone at the school', '在学校的所有人', 147, 1, 1),
  ('ket-trainer-test4-reading-part1-395-synonym-miss-a-class-couldnt-go-to-a-lesson-885c3ff6', 'synonym', 'ket', 'KET Trainer', 'Test4 Reading Part1', 'Miss a class', '错过课程', 'couldn’t go to a lesson', '没能去上课', 148, 1, 1),
  ('ket-trainer-test4-reading-part2-399-synonym-received-4000-won-a-prize-924dbb12', 'synonym', 'ket', 'KET Trainer', 'Test4 Reading Part2', 'Received £4000', '得到 4000 英镑', 'won a prize', '赢得奖品', 149, 1, 1),
  ('ket-trainer-test4-reading-part2-401-synonym-good-for-you-healthy-83f9d342', 'synonym', 'ket', 'KET Trainer', 'Test4 Reading Part2', 'Good for you', '对你很好', 'healthy', '健康的', 150, 1, 1),
  ('ket-trainer-test4-reading-part2-403-synonym-can-enjoy-can-be-fun-6993f042', 'synonym', 'ket', 'KET Trainer', 'Test4 Reading Part2', 'Can enjoy', '可以享受', 'can be fun', '可以很有趣', 151, 1, 1),
  ('ket-trainer-test4-reading-part2-405-synonym-from-all-four-corners-of-the-world-from-different-countries-9e8b8659', 'synonym', 'ket', 'KET Trainer', 'Test4 Reading Part2', 'From all four corners of the world', '来自世界各地', 'from different countries', '来自不同国家', 152, 1, 1),
  ('ket-trainer-test4-reading-part2-407-synonym-names-about-food-food-words-03be19b3', 'synonym', 'ket', 'KET Trainer', 'Test4 Reading Part2', 'Names about food', '关于食物的名字', 'food words', '食物单词', 153, 1, 1),
  ('ket-trainer-test4-reading-part3-411-synonym-couldnt-wait-to-excited-about-4f9aee68', 'synonym', 'ket', 'KET Trainer', 'Test4 Reading Part3', 'Couldn’t wait to', '迫不及待做', 'excited about', '对...很兴奋', 154, 1, 1),
  ('ket-trainer-test4-reading-part3-413-synonym-bright-not-dark-5961e89a', 'synonym', 'ket', 'KET Trainer', 'Test4 Reading Part3', 'Bright', '明亮的', 'not dark', '不黑', 155, 1, 1),
  ('ket-trainer-test4-reading-part3-415-synonym-loud-music-noisy-d16051b8', 'synonym', 'ket', 'KET Trainer', 'Test4 Reading Part3', 'Loud music', '大声的音乐', 'noisy', '很吵', 156, 1, 1),
  ('ket-trainer-test4-reading-part3-417-synonym-there-werent-many-people-not-buy-024b98ad', 'synonym', 'ket', 'KET Trainer', 'Test4 Reading Part3', 'There weren’t many people', '没有很多人', 'not buy', '不忙', 157, 1, 1),
  ('ket-trainer-test4-reading-part3-419-synonym-top-of-the-building-roof-897b597f', 'synonym', 'ket', 'KET Trainer', 'Test4 Reading Part3', 'Top of the building', '建筑的顶部', 'roof', '屋顶', 158, 1, 1),
  ('ket-trainer-test4-reading-part3-421-synonym-large-so-big-b9b11be7', 'synonym', 'ket', 'KET Trainer', 'Test4 Reading Part3', 'Large', '巨大的', 'so big', '非常大', 159, 1, 1),
  ('ket-trainer-test4-reading-part3-423-synonym-that-was-really-cool-enjoy-doing-most-0a1dfaa6', 'synonym', 'ket', 'KET Trainer', 'Test4 Reading Part3', 'That was really cool', '那太酷了', 'enjoy doing most', '最喜欢做', 160, 1, 1),
  ('ket-trainer-test4-listening-part1-427-synonym-winner-first-prize-cb3d092b', 'synonym', 'ket', 'KET Trainer', 'Test4 Listening Part1', 'winner', '胜利者', 'first prize', '一等奖', 161, 1, 1),
  ('ket-trainer-test4-listening-part4-433-synonym-underground-train-e34b2dee', 'synonym', 'ket', 'KET Trainer', 'Test4 Listening Part4', 'underground', '地铁', 'train', '列车', 162, 1, 1),
  ('ket-trainer-test4-listening-part4-435-synonym-folder-plactic-box-with-school-papers-19d09bdf', 'synonym', 'ket', 'KET Trainer', 'Test4 Listening Part4', 'folder', '文件夹', 'plactic box with school papers', '装学校文件的塑料盒', 163, 1, 1),
  ('ket-trainer-test4-listening-part4-437-synonym-funny-films-with-talking-animals-cartoons-71b53ba3', 'synonym', 'ket', 'KET Trainer', 'Test4 Listening Part4', 'Funny films with talking animals', '有会说话动物的搞笑电影', 'cartoons', '卡通片', 164, 1, 1),
  ('ket-trainer-test4-listening-part4-439-synonym-brush-abd-feed-the-horses-look-after-animals-e659c0fa', 'synonym', 'ket', 'KET Trainer', 'Test4 Listening Part4', 'Brush abd feed the horses', '给马刷毛和喂马', 'look after animals', '照顾动物', 165, 1, 1),
  ('ket-trainer-test4-listening-part4-445-synonym-somewhere-to-buy-and-eat-lunch-cafeteria-6ce0aac9', 'synonym', 'ket', 'KET Trainer', 'Test4 Listening Part4', 'Somewhere to buy and eat lunch', '某个买午餐和吃午餐的地方', 'cafeteria', '食堂', 166, 1, 1),
  ('ket-trainer-test4-listening-part5-449-synonym-i-can-fly-it-on-the-hill-kite-b999464f', 'synonym', 'ket', 'KET Trainer', 'Test4 Listening Part5', 'I can fly it on the hill', '我可以在山上放飞它', 'kite', '风筝', 167, 1, 1),
  ('ket-trainer-test4-listening-part5-451-synonym-put-pictures-in-it-photo-album-3115362a', 'synonym', 'ket', 'KET Trainer', 'Test4 Listening Part5', 'Put pictures in it', '把照片放进去', 'photo album', '相册', 168, 1, 1),
  ('ket-trainer-test4-listening-part5-453-synonym-write-down-what-shes-doing-on-each-date-calendar-c825b5cb', 'synonym', 'ket', 'KET Trainer', 'Test4 Listening Part5', 'Write down what she’s doing on each date', '在每一天上写她做的事情', 'calendar', '日历', 169, 1, 1),
  ('ket-trainer-test4-listening-part5-455-synonym-look-up-words-dictionary-4af82ab8', 'synonym', 'ket', 'KET Trainer', 'Test4 Listening Part5', 'Look up words', '查单词', 'dictionary', '字典', 170, 1, 1),
  ('ket-trainer-test4-listening-part5-457-synonym-cup-mug-c1525bef', 'synonym', 'ket', 'KET Trainer', 'Test4 Listening Part5', 'Cup', '杯子', 'mug', '马克杯', 171, 1, 1),
  ('ket-trainer-test4-listening-part5-459-synonym-put-school-books-in-it-backpack-e9451773', 'synonym', 'ket', 'KET Trainer', 'Test4 Listening Part5', 'Put school books in it', '把学校的书放里面', 'backpack', '背包', 172, 1, 1),
  ('ket-trainer-test5-reading-part1-465-synonym-arent-opend-havent-used-it-41091ced', 'synonym', 'ket', 'KET Trainer', 'Test5 Reading Part1', 'aren’t opend', '没有开过的', 'haven’t used it', '没有使用过的', 173, 1, 1),
  ('ket-trainer-test5-reading-part1-467-synonym-join-the-book-club-become-a-member-of-the-book-club-a6c64b35', 'synonym', 'ket', 'KET Trainer', 'Test5 Reading Part1', 'Join the book club', '加入读书俱乐部', 'become a member of the book club', '成为读书俱乐部的 会员', 174, 1, 1),
  ('ket-trainer-test5-reading-part1-471-synonym-miss-a-class-couldnt-go-to-a-lesson-21536ff8', 'synonym', 'ket', 'KET Trainer', 'Test5 Reading Part1', 'Miss a class', '错过课程', 'couldn’t go to a lesson', '没能去上课', 175, 1, 1),
  ('ket-trainer-test5-reading-part2-475-synonym-give-money-to-nature-group-work-with-bees-help-wildlifes-06068668', 'synonym', 'ket', 'KET Trainer', 'Test5 Reading Part2', 'give money to nature group work with bees', '捐钱给研究蜜蜂的自然组织', 'help wildlifes', '帮助 野生动物', 176, 1, 1),
  ('ket-trainer-test5-reading-part2-479-synonym-give-someone-a-job-pay-someone-to-help-her-85dbf31f', 'synonym', 'ket', 'KET Trainer', 'Test5 Reading Part2', 'give someone a job', '给某人一份工作', 'pay someone to help her', '付钱给某人帮她忙', 177, 1, 1),
  ('ket-trainer-test5-reading-part2-481-synonym-nature-flowers-and-plants-f7a66a90', 'synonym', 'ket', 'KET Trainer', 'Test5 Reading Part2', 'nature', '大自然', 'flowers and plants', '花和植物', 178, 1, 1),
  ('ket-trainer-test5-reading-part2-483-synonym-show-children-how-to-teach-children-f8671f36', 'synonym', 'ket', 'KET Trainer', 'Test5 Reading Part2', 'Show children how to', '给孩子展示怎么', 'teach children', '教孩子', 179, 1, 1),
  ('ket-trainer-test5-reading-part2-485-synonym-begin-a-business-open-a-company-74068052', 'synonym', 'ket', 'KET Trainer', 'Test5 Reading Part2', 'begin a business', '创业', 'open a company', '开一家公司', 180, 1, 1),
  ('ket-trainer-test5-reading-part2-487-synonym-happy-pleased-6b2fe5f4', 'synonym', 'ket', 'KET Trainer', 'Test5 Reading Part2', 'happy', '开心的', 'pleased', '高兴的', 181, 1, 1),
  ('ket-trainer-test5-reading-part3-491-synonym-improve-get-better-at-81fc3a8d', 'synonym', 'ket', 'KET Trainer', 'Test5 Reading Part3', 'improve', '进步', 'get better at', '在...方面变得更好', 182, 1, 1),
  ('ket-trainer-test5-reading-part3-493-synonym-share-a-flat-live-together-5e4038b1', 'synonym', 'ket', 'KET Trainer', 'Test5 Reading Part3', 'share a flat', '合住一套公寓', 'live together', '在一起住', 183, 1, 1),
  ('ket-trainer-test5-reading-part3-495-synonym-better-known-than-more-famous-than-b2cde1e9', 'synonym', 'ket', 'KET Trainer', 'Test5 Reading Part3', 'better-known than', '比...更知名', 'more famous than', '比...更有名', 184, 1, 1),
  ('ket-trainer-test5-reading-part3-497-synonym-add-include-81c5ad89', 'synonym', 'ket', 'KET Trainer', 'Test5 Reading Part3', 'add', '加', 'include', '包含', 185, 1, 1),
  ('ket-trainer-test5-listening-part3-503-synonym-all-my-friends-have-is-popular-4b7c4e2a', 'synonym', 'ket', 'KET Trainer', 'Test5 Listening Part3', 'All my friends have', '我所有的朋友都有', 'is popular', '很流行', 186, 1, 1),
  ('ket-trainer-test5-listening-part3-507-synonym-beginner-people-who-are-new-a18b4173', 'synonym', 'ket', 'KET Trainer', 'Test5 Listening Part3', 'beginner', '初学者', 'people who are new', '新手', 187, 1, 1),
  ('ket-trainer-test5-listening-part4-511-synonym-a-explained-to-b-a-b-listened-to-a-talk-from-a-b-0ee1efdb', 'synonym', 'ket', 'KET Trainer', 'Test5 Listening Part4', 'A explained .. to B A', '解释..给 B', 'B listened to a talk from A B', '听了 A 的一段讲话', 188, 1, 1),
  ('ket-trainer-test5-listening-part4-517-synonym-neighbour-people-who-live-near-him-ba569aed', 'synonym', 'ket', 'KET Trainer', 'Test5 Listening Part4', 'neighbour', '邻居', 'people who live near him', '住的离他近的人', 189, 1, 1),
  ('ket-trainer-test5-listening-part4-519-synonym-group-leader-guide-4ccd7c95', 'synonym', 'ket', 'KET Trainer', 'Test5 Listening Part4', 'group leader', '组长', 'guide', '引导者', 190, 1, 1),
  ('ket-trainer-test5-listening-part4-521-synonym-skateboard-sport-8b841d2f', 'synonym', 'ket', 'KET Trainer', 'Test5 Listening Part4', 'skateboard', '滑板', 'sport', '运动', 191, 1, 1),
  ('ket-trainer-test5-listening-part4-523-synonym-have-match-inside-sports-hall-d18ce542', 'synonym', 'ket', 'KET Trainer', 'Test5 Listening Part4', 'have match inside', '在里面比赛', 'sports hall', '体育馆', 192, 1, 1),
  ('ket-trainer-test5-listening-part4-525-synonym-get-dirt-out-of-the-fur-brush-96bd277b', 'synonym', 'ket', 'KET Trainer', 'Test5 Listening Part4', 'get dirt out of the fur', '把泥土从毛上弄走', 'brush', '梳毛', 193, 1, 1),
  ('ket-trainer-test5-listening-part4-527-synonym-horrible-dont-like-bd1844bf', 'synonym', 'ket', 'KET Trainer', 'Test5 Listening Part4', 'horrible', '可怕的', 'don’t like', '不喜欢', 194, 1, 1),
  ('ket-trainer-test5-listening-part5-531-synonym-take-fifty-five-pounds-take-money-d8f8a2b9', 'synonym', 'ket', 'KET Trainer', 'Test5 Listening Part5', 'take fifty-five pounds', '带 55 英镑', 'take money', '带钱', 195, 1, 1),
  ('ket-trainer-test5-listening-part5-533-synonym-neighbour-people-who-next-door-474f5dcf', 'synonym', 'ket', 'KET Trainer', 'Test5 Listening Part5', 'neighbour', '邻居', 'people who next door', '住在隔壁的人', 196, 1, 1),
  ('ket-trainer-test5-listening-part5-535-synonym-cook-supper-make-a-meal-cbc58095', 'synonym', 'ket', 'KET Trainer', 'Test5 Listening Part5', 'cook supper', '做晚餐', 'make a meal', '做一顿饭', 197, 1, 1),
  ('ket-trainer-test6-reading-part1-541-synonym-books-library-001c9bb9', 'synonym', 'ket', 'KET Trainer', 'Test6 Reading Part1', 'books', '', 'library', '图书馆', 198, 1, 1),
  ('ket-trainer-test6-reading-part1-543-synonym-cinema-see-a-film-e5f26362', 'synonym', 'ket', 'KET Trainer', 'Test6 Reading Part1', 'cinema', '电影院', 'see a film', '看电影', 199, 1, 1),
  ('ket-trainer-test6-reading-part1-545-synonym-passed-math-done-well-in-an-exam-85651318', 'synonym', 'ket', 'KET Trainer', 'Test6 Reading Part1', 'passed math', '通过了数学考试', 'done well in an exam', '在考试里表现不错', 200, 1, 1),
  ('ket-trainer-test6-reading-part1-547-synonym-no-exit-you-cant-go-through-this-door-625744b4', 'synonym', 'ket', 'KET Trainer', 'Test6 Reading Part1', 'NO EXIT', '此路不通', 'you can’t go through this door', '你不能从这扇门进去', 201, 1, 1),
  ('ket-trainer-test6-reading-part1-549-synonym-guest-party-c848da83', 'synonym', 'ket', 'KET Trainer', 'Test6 Reading Part1', 'guest', '客人', 'party', '派对', 202, 1, 1),
  ('ket-trainer-test6-reading-part2-553-synonym-friends-mates-d70e82ab', 'synonym', 'ket', 'KET Trainer', 'Test6 Reading Part2', 'friends', '朋友', 'mates', '朋友，伙伴', 203, 1, 1),
  ('ket-trainer-test6-reading-part2-555-synonym-a-minute-or-two-from-our-apartment-near-our-home-a181fd59', 'synonym', 'ket', 'KET Trainer', 'Test6 Reading Part2', 'a minute or two from our apartment', '离我们公寓一两分钟', 'near our home', '离我们家近', 204, 1, 1),
  ('ket-trainer-test6-reading-part2-557-synonym-getting-better-at-improving-74af1bc3', 'synonym', 'ket', 'KET Trainer', 'Test6 Reading Part2', 'getting better at', '在...变得更好', 'improving', '进步中', 205, 1, 1),
  ('ket-trainer-test6-reading-part2-559-synonym-family-member-cousin-34480983', 'synonym', 'ket', 'KET Trainer', 'Test6 Reading Part2', 'family member', '家庭成员', 'cousin', '堂/表兄弟姐妹', 206, 1, 1),
  ('ket-trainer-test6-reading-part2-561-synonym-buy-something-order-some-new-running-shoes-c853ac73', 'synonym', 'ket', 'KET Trainer', 'Test6 Reading Part2', 'buy something', '买东西', 'order some new running shoes', '订购一些新的跑步鞋', 207, 1, 1),
  ('ket-trainer-test6-reading-part3-565-synonym-quickly-fast-3e36d651', 'synonym', 'ket', 'KET Trainer', 'Test6 Reading Part3', 'quickly', '快地', 'fast', '快', 208, 1, 1),
  ('ket-trainer-test6-reading-part3-567-synonym-do-things-together-with-your-colleagues-work-well-with-other-people-3db2518c', 'synonym', 'ket', 'KET Trainer', 'Test6 Reading Part3', 'do things together with your colleagues', '和同事一起做事', 'work well with other people', '和他 人和谐共事', 209, 1, 1),
  ('ket-trainer-test6-reading-part3-571-synonym-go-leave-651cf65a', 'synonym', 'ket', 'KET Trainer', 'Test6 Reading Part3', 'go', '去', 'leave', '离开', 210, 1, 1),
  ('ket-trainer-test6-listening-part3-577-synonym-cycle-by-bike-f66332c4', 'synonym', 'ket', 'KET Trainer', 'Test6 Listening Part3', 'cycle', '骑自行车', 'by bike', '骑自行车', 211, 1, 1),
  ('ket-trainer-test6-listening-part3-579-synonym-doesnt-like-boring-94a5a3cc', 'synonym', 'ket', 'KET Trainer', 'Test6 Listening Part3', 'doesn’t like', '不喜欢', 'boring', '无聊的', 212, 1, 1),
  ('ket-trainer-test6-listening-part3-583-synonym-around-about-eebf94d1', 'synonym', 'ket', 'KET Trainer', 'Test6 Listening Part3', 'around', '大约', 'about', '大约', 213, 1, 1),
  ('ket-trainer-test6-listening-part3-585-synonym-talk-to-teachers-meet-teachers-118c1acd', 'synonym', 'ket', 'KET Trainer', 'Test6 Listening Part3', 'talk to teachers', '和老师谈话', 'meet teachers', '见老师', 214, 1, 1),
  ('ket-trainer-test6-listening-part4-589-synonym-cheaper-cost-3d3ef481', 'synonym', 'ket', 'KET Trainer', 'Test6 Listening Part4', 'cheaper', '更便宜', 'cost', '花费', 215, 1, 1),
  ('ket-trainer-test6-listening-part4-591-synonym-bus-transport-97cff180', 'synonym', 'ket', 'KET Trainer', 'Test6 Listening Part4', 'bus', '巴士', 'transport', '交通', 216, 1, 1),
  ('ket-trainer-test6-listening-part4-593-synonym-in-the-drawer-in-the-desk-46890d92', 'synonym', 'ket', 'KET Trainer', 'Test6 Listening Part4', 'in the drawer', '在抽屉里', 'in the desk', '在书桌里', 217, 1, 1),
  ('ket-trainer-test6-listening-part4-595-synonym-bag-backpack-d31aaa5d', 'synonym', 'ket', 'KET Trainer', 'Test6 Listening Part4', 'bag', '包', 'backpack', '背包', 218, 1, 1),
  ('ket-trainer-test6-listening-part4-597-synonym-singer-is-wearing-in-fashion-6596bdd2', 'synonym', 'ket', 'KET Trainer', 'Test6 Listening Part4', 'singer is wearing', '歌手在穿的', 'in fashion', '时尚', 219, 1, 1),
  ('ket-trainer-test6-listening-part4-599-synonym-angry-mad-9d742a6e', 'synonym', 'ket', 'KET Trainer', 'Test6 Listening Part4', 'angry', '生气的', 'mad', '生气的', 220, 1, 1),
  ('ket-trainer-test6-listening-part4-601-synonym-always-want-to-help-friendly-5dc75f41', 'synonym', 'ket', 'KET Trainer', 'Test6 Listening Part4', 'always want to help', '总是想帮忙', 'friendly', '友好地', 221, 1, 1),
  ('ket-trainer-test6-listening-part5-605-synonym-i-can-use-useful-8181379e', 'synonym', 'ket', 'KET Trainer', 'Test6 Listening Part5', 'I can use', '我可以使用', 'useful', '有用的', 222, 1, 1),
  ('ket-trainer-test6-listening-part5-607-synonym-finish-too-quickly-too-short-749705eb', 'synonym', 'ket', 'KET Trainer', 'Test6 Listening Part5', 'finish too quickly', '太快就完成了', 'too short', '太短了', 223, 1, 1),
  ('ket-trainer-test6-listening-part5-609-synonym-made-me-laugh-funny-cec4f463', 'synonym', 'ket', 'KET Trainer', 'Test6 Listening Part5', 'made me laugh', '让我笑', 'funny', '有趣的', 224, 1, 1),
  ('ket-trainer-test6-listening-part5-611-synonym-difficult-to-read-hard-to-understand-4db949bc', 'synonym', 'ket', 'KET Trainer', 'Test6 Listening Part5', 'difficult to read', '很难阅读', 'hard to understand', '理解起来很困难', 225, 1, 1),
  ('ket-trainer-test6-listening-part5-613-synonym-cry-sad-83bec54b', 'synonym', 'ket', 'KET Trainer', 'Test6 Listening Part5', 'cry', '哭', 'sad', '伤心', 226, 1, 1),
  ('ket-trainer-test6-listening-part5-615-synonym-first-was-best-good-beginning-f25fc7f3', 'synonym', 'ket', 'KET Trainer', 'Test6 Listening Part5', 'first was best', '最开始的是最好的', 'good beginning', '好的开始', 227, 1, 1),
  ('ket-complete-unit1-students-book-007-synonym-on-offer-cheaper-3a7d9a0e', 'synonym', 'ket', 'KET Complete', 'Unit1 Students book', 'on offer', '降价出售', 'cheaper', '更便宜', 228, 1, 1),
  ('ket-complete-unit1-students-book-009-synonym-thats-the-best-one-favourite-9dd846aa', 'synonym', 'ket', 'KET Complete', 'Unit1 Students book', 'That’s the best one', '那是最好的', 'favourite', '最爱的', 229, 1, 1),
  ('ket-complete-unit1-students-book-011-synonym-doesnt-like-hate-05b3d538', 'synonym', 'ket', 'KET Complete', 'Unit1 Students book', 'doesn''t like', '不喜欢', 'hate', '讨厌', 230, 1, 1),
  ('ket-complete-unit1-students-book-013-synonym-pet-dog-cat-fish-95ac5726', 'synonym', 'ket', 'KET Complete', 'Unit1 Students book', 'pet', '宠物', 'dog,cat,fish', '', 231, 1, 1),
  ('ket-complete-unit1-students-book-015-synonym-from-another-country-from-poland-616055ab', 'synonym', 'ket', 'KET Complete', 'Unit1 Students book', 'From another country', '来自另一个国家', 'from Poland', '来自波兰', 232, 1, 1),
  ('ket-complete-unit1-students-book-017-synonym-musical-instrument-piano-faf29853', 'synonym', 'ket', 'KET Complete', 'Unit1 Students book', 'Musical instrument', '乐器', 'piano', '钢琴', 233, 1, 1),
  ('ket-complete-unit1-workbook-021-synonym-new-film-the-latest-film-df76a7e4', 'synonym', 'ket', 'KET Complete', 'Unit1 workbook', 'new film', '新电影', 'the latest film', '最近的电影', 234, 1, 1),
  ('ket-complete-unit1-workbook-023-synonym-stay-at-home-come-to-my-house-and-watch-a-film-afd09c87', 'synonym', 'ket', 'KET Complete', 'Unit1 workbook', 'Stay at home', '待在家', 'come to my house and watch a film', '来我家看电影', 235, 1, 1),
  ('ket-complete-unit1-workbook-025-synonym-live-close-to-live-on-the-same-street-219fc17c', 'synonym', 'ket', 'KET Complete', 'Unit1 workbook', 'Live close to', '住的离...近', 'live on the same street', '住在同一条街上', 236, 1, 1),
  ('ket-complete-unit1-workbook-027-synonym-enjoy-doing-sport-love-playing-the-game-89593400', 'synonym', 'ket', 'KET Complete', 'Unit1 workbook', 'Enjoy doing sport', '享受做运动', 'love playing the game', '喜欢打比赛', 237, 1, 1),
  ('ket-complete-unit1-workbook-029-synonym-doesnt-like-a-bit-boring-b0e7fc14', 'synonym', 'ket', 'KET Complete', 'Unit1 workbook', 'doesn''t like', '不喜欢', 'a bit boring', '有一点无聊', 238, 1, 1),
  ('ket-complete-unit1-workbook-031-synonym-see-his-friends-meet-my-classmates-c6e231d9', 'synonym', 'ket', 'KET Complete', 'Unit1 workbook', 'See his friends', '见朋友', 'meet my classmates', '见同学', 239, 1, 1),
  ('ket-complete-unit2-students-book-035-synonym-have-dinner-after-i-finish-my-homework-doesnt-want-dinner-before-finish-my-homework-fb69406f', 'synonym', 'ket', 'KET Complete', 'Unit2 Students book', 'Have dinner after I finish my homework', '完 成 作 业 后 吃 晚 餐', 'doesn’t want dinner before finish my homework', '在完成作业前不想吃晚餐', 240, 1, 1),
  ('ket-complete-unit2-students-book-039-synonym-give-me-half-of-the-money-share-the-cost-09e977c5', 'synonym', 'ket', 'KET Complete', 'Unit2 Students book', 'Give me half of the money', '给我一半的钱', 'share the cost', '分享花费', 241, 1, 1),
  ('ket-complete-unit2-students-book-041-synonym-free-food-for-children-children-dont-have-to-pay-cfd2fb03', 'synonym', 'ket', 'KET Complete', 'Unit2 Students book', 'Free food for children', '孩子的食物免费', 'children don’t have to pay', '孩子不需要付钱', 242, 1, 1),
  ('ket-complete-unit2-students-book-043-synonym-go-afterwards-go-to-the-party-late-a61b2c1b', 'synonym', 'ket', 'KET Complete', 'Unit2 Students book', 'Go afterwards', '之后去', 'go to the party late', '晚点去派对', 243, 1, 1),
  ('ket-complete-unit2-students-book-045-synonym-class-is-in-room-4-today-lesson-is-in-a-different-place-today-493854df', 'synonym', 'ket', 'KET Complete', 'Unit2 Students book', 'Class is in room 4 today', '课今天在 4 号房', 'lesson is in a different place today', '课在不同的地方', 244, 1, 1),
  ('ket-complete-unit2-workbook-049-synonym-tell-me-what-you-think-give-him-opinion-ba43f18a', 'synonym', 'ket', 'KET Complete', 'Unit2 workbook', 'Tell me what you think', '告诉我你怎么想的', 'give him opinion', '给他意见', 245, 1, 1),
  ('ket-complete-unit2-workbook-051-synonym-all-students-wecome-everyone-is-invited-e52e013c', 'synonym', 'ket', 'KET Complete', 'Unit2 workbook', 'All students wecome', '欢迎所有学生', 'everyone is invited', '所有人都被邀请', 246, 1, 1),
  ('ket-complete-unit2-workbook-053-synonym-bring-it-to-school-take-something-to-school-7f9437a1', 'synonym', 'ket', 'KET Complete', 'Unit2 workbook', 'Bring it to school', '把它带到学校', 'take something to school', '带某物到学校', 247, 1, 1),
  ('ket-complete-unit2-workbook-055-synonym-left-at-home-something-hes-forgotten-f17b1b80', 'synonym', 'ket', 'KET Complete', 'Unit2 workbook', 'Left...at home', '把..忘在家', 'something he’s forgotten', '某个他遗忘的东西', 248, 1, 1),
  ('ket-complete-unit2-workbook-057-synonym-opening-new-restaurant-810f66e8', 'synonym', 'ket', 'KET Complete', 'Unit2 workbook', 'Opening', '开业', 'new restaurant', '新的（餐馆）', 249, 1, 1),
  ('ket-complete-unit2-workbook-059-synonym-give-us-a-lift-home-collect-us-86ea9fe7', 'synonym', 'ket', 'KET Complete', 'Unit2 workbook', 'Give us a lift home', '开车送我们回家', 'collect us', '接我们', 250, 1, 1),
  ('ket-complete-unit2-workbook-061-synonym-dont-keep-it-for-more-than-two-days-only-keep-it-for-two-days-912128b7', 'synonym', 'ket', 'KET Complete', 'Unit2 workbook', 'Don’t keep it for more than two days', '不要保留超过两天', 'only keep it for two days', '只能保留 两天', 251, 1, 1),
  ('ket-complete-unit3-students-book-067-synonym-started-cooking-made-my-first-meal-66ef6f2a', 'synonym', 'ket', 'KET Complete', 'Unit3 Students book', 'Started cooking', '开始做饭', 'made my first meal', '做我第一顿饭', 252, 1, 1),
  ('ket-complete-unit3-students-book-069-synonym-include-fish-use-one-kind-of-food-99cf466e', 'synonym', 'ket', 'KET Complete', 'Unit3 Students book', 'Include fish', '包含鱼', 'use one kind of food', '使用一种食材', 253, 1, 1),
  ('ket-complete-unit3-students-book-071-synonym-usually-not-always-f5f2e6b2', 'synonym', 'ket', 'KET Complete', 'Unit3 Students book', 'Usually', '通常', 'not always', '不总是', 254, 1, 1),
  ('ket-complete-unit3-students-book-073-synonym-surprised-amazed-daa8fc18', 'synonym', 'ket', 'KET Complete', 'Unit3 Students book', 'Surprised', '惊讶的', 'amazed', '惊讶的', 255, 1, 1),
  ('ket-complete-unit3-students-book-075-synonym-fun-enjoy-myself-doing-it-a8498599', 'synonym', 'ket', 'KET Complete', 'Unit3 Students book', 'Fun', '有趣的', 'enjoy myself doing it', '享受做它', 256, 1, 1),
  ('ket-complete-unit3-workbook-079-synonym-its-never-busy-its-not-usually-full-c83c29fd', 'synonym', 'ket', 'KET Complete', 'Unit3 workbook', 'It’s never busy', '它不忙', 'it’s not usually full', '它通常不满（餐馆）', 257, 1, 1),
  ('ket-complete-unit3-workbook-081-synonym-has-a-lot-of-car-driving-along-on-a-busy-road-ce322669', 'synonym', 'ket', 'KET Complete', 'Unit3 workbook', 'Has a lot of car driving along', '有很多车开过', 'on a busy road', '在一条很繁忙的街道', 258, 1, 1),
  ('ket-complete-unit3-workbook-083-synonym-always-come-to-say-hello-friendly-2372fd32', 'synonym', 'ket', 'KET Complete', 'Unit3 workbook', 'Always come to say hello', '总是过来打招呼', 'friendly', '友好地', 259, 1, 1),
  ('ket-complete-unit3-workbook-085-synonym-waiter-staff-7a0bf70f', 'synonym', 'ket', 'KET Complete', 'Unit3 workbook', 'Waiter', '服务员', 'staff', '员工', 260, 1, 1),
  ('ket-complete-unit3-workbook-087-synonym-dont-know-which-to-have-cant-decide-what-to-order-173079d7', 'synonym', 'ket', 'KET Complete', 'Unit3 workbook', 'Don’t know which to have', '不知道吃哪一个', 'can’t decide what to order', '不能决定点什么', 261, 1, 1),
  ('ket-complete-unit3-workbook-089-synonym-teach-me-to-cook-what-we-have-make-the-dish-myself-8699f934', 'synonym', 'ket', 'KET Complete', 'Unit3 workbook', 'Teach me to cook what we have', '教我做我们吃的', 'make the dish myself', '自己做这道菜', 262, 1, 1),
  ('ket-complete-unit5-students-book-093-synonym-have-some-time-to-myself-be-alone-9e33918d', 'synonym', 'ket', 'KET Complete', 'Unit5 Students book', 'Have some time to myself', '有自己的时间', 'be alone', '独自一个人', 263, 1, 1),
  ('ket-complete-unit5-students-book-095-synonym-a-variety-of-activities-everyday-theres-something-different-to-do-b0fdc34d', 'synonym', 'ket', 'KET Complete', 'Unit5 Students book', 'A variety of activities', '各种各样的活动', 'everyday there’s something different to do', '每天 都有不同的事做', 264, 1, 1),
  ('ket-complete-unit5-students-book-099-synonym-cant-spend-more-time-cant-go-more-often-1df02b71', 'synonym', 'ket', 'KET Complete', 'Unit5 Students book', 'Can’t Spend more time', '不能花更多的时间', 'can’t go more often', '不能更频繁的去', 265, 1, 1),
  ('ket-complete-unit5-students-book-101-synonym-its-a-pity-that-im-sad-that-e38f793b', 'synonym', 'ket', 'KET Complete', 'Unit5 Students book', 'It’s a pity that', '很遗憾', 'I’m sad that', '我很伤心', 266, 1, 1),
  ('ket-complete-unit5-students-book-103-synonym-spend-time-together-go-for-a-picnic-watch-tv-together-a60c519d', 'synonym', 'ket', 'KET Complete', 'Unit5 Students book', 'Spend time together', '花时间待一起', 'go for a picnic,watch TV together', '一起野餐，看电视', 267, 1, 1),
  ('ket-complete-unit5-students-book-105-synonym-dont-give-it-to-others-immediately-keep-it-for-longer-2f4eedfb', 'synonym', 'ket', 'KET Complete', 'Unit5 Students book', 'Don’t give it to others immediately', '不要马上给别人', 'keep it for longer', '保留更久的时间', 268, 1, 1),
  ('ket-complete-unit5-students-book-107-synonym-dark-not-light-enough-aeae20fc', 'synonym', 'ket', 'KET Complete', 'Unit5 Students book', 'Dark', '黑暗的', 'not light enough', '不够亮', 269, 1, 1),
  ('ket-complete-unit5-students-book-109-synonym-get-the-best-board-you-can-spend-much-money-on-a-board-5ce7292c', 'synonym', 'ket', 'KET Complete', 'Unit5 Students book', 'Get the best board you can', '尽可能买最好的板', 'spend much money on a board', '在板上 花很多钱', 270, 1, 1),
  ('ket-complete-unit5-students-book-113-synonym-it-takes-time-and-practice-its-not-easy-f99ddddf', 'synonym', 'ket', 'KET Complete', 'Unit5 Students book', 'It takes time and practice', '它要花时间和练习', 'it’s not easy', '他不容易', 271, 1, 1),
  ('ket-complete-unit5-workbook-117-synonym-usually-almost-everyday-0fd93267', 'synonym', 'ket', 'KET Complete', 'Unit5 workbook', 'Usually', '通常', 'almost everyday', '几乎每天', 272, 1, 1),
  ('ket-complete-unit5-workbook-119-synonym-favourite-like-the-most-0345d647', 'synonym', 'ket', 'KET Complete', 'Unit5 workbook', 'Favourite', '最爱', 'like the most', '最喜欢的', 273, 1, 1),
  ('ket-complete-unit5-workbook-121-synonym-want-to-know-about-ask-about-fcac7a3f', 'synonym', 'ket', 'KET Complete', 'Unit5 workbook', 'Want to know about', '想要知道关于...的', 'ask about', '提问关于', 274, 1, 1),
  ('ket-complete-unit5-workbook-123-synonym-didnt-expect-to-come-first-didnt-want-to-win-6fd3c637', 'synonym', 'ket', 'KET Complete', 'Unit5 workbook', 'Didn’t expect to come first', '没期待得第一', 'didn’t want to win', '没想要赢', 275, 1, 1),
  ('ket-complete-unit5-workbook-125-synonym-didnt-pay-much-cheap-fa4abeef', 'synonym', 'ket', 'KET Complete', 'Unit5 workbook', 'Didn’t pay much', '没有付很多钱', 'cheap', '便宜的', 276, 1, 1),
  ('ket-complete-unit5-workbook-127-synonym-my-sisters-belong-to-a-family-member-661b0b3b', 'synonym', 'ket', 'KET Complete', 'Unit5 workbook', 'My sister’s', '我妹妹的', 'belong to a family member', '属于一个家庭成员', 277, 1, 1),
  ('ket-complete-unit5-workbook-129-synonym-do-exercise-at-a-gym-e2d8baf9', 'synonym', 'ket', 'KET Complete', 'Unit5 workbook', 'Do exercise', '锻炼,have a shower 洗澡', 'at a gym', '在健身房', 278, 1, 1),
  ('ket-complete-unit5-workbook-131-synonym-brilliant-fantastic-1873a1df', 'synonym', 'ket', 'KET Complete', 'Unit5 workbook', 'Brilliant', '出色的', 'fantastic', '极好的', 279, 1, 1),
  ('ket-complete-unit5-workbook-133-synonym-spend-a-lot-of-time-with-coach-do-a-lot-of-practice-db1bc974', 'synonym', 'ket', 'KET Complete', 'Unit5 workbook', 'Spend a lot of time with coach', '花很多时间和教练一起', 'do a lot of practice', '做了很多训 练', 280, 1, 1),
  ('ket-complete-unit6-students-book-139-synonym-dont-start-until-9-oclock-start-at-9-oclock-4f7e80b7', 'synonym', 'ket', 'KET Complete', 'Unit6 Students book', 'Don’t start until 9 o’clock', '直到 9 点才开始', 'start at 9 o’clock', '在 9 点开始', 281, 1, 1),
  ('ket-complete-unit6-students-book-141-synonym-tell-sb-how-to-do-things-clearly-good-at-explaining-things-40eca3d9', 'synonym', 'ket', 'KET Complete', 'Unit6 Students book', 'Tell sb. how to do things clearly', '清晰的告诉某人如何做', 'good at explaining things', '擅长 解释事情', 282, 1, 1),
  ('ket-complete-unit6-students-book-145-synonym-make-sb-laugh-funny-cdf7f268', 'synonym', 'ket', 'KET Complete', 'Unit6 Students book', 'Make sb. laugh', '使...发笑', 'funny', '有趣的', 283, 1, 1),
  ('ket-complete-unit6-students-book-147-synonym-famous-football-player-sports-star-42f7e886', 'synonym', 'ket', 'KET Complete', 'Unit6 Students book', 'Famous football player', '有名的足球运动员', 'sports star', '运动明星', 284, 1, 1),
  ('ket-complete-unit6-students-book-149-synonym-at-the-moment-now-c87e30aa', 'synonym', 'ket', 'KET Complete', 'Unit6 Students book', 'At the moment', '在此刻', 'now', '现在', 285, 1, 1),
  ('ket-complete-unit6-students-book-151-synonym-learn-from-two-people-my-parents-teach-me-30043303', 'synonym', 'ket', 'KET Complete', 'Unit6 Students book', 'Learn from two people', '从两人学习', 'my parents teach me', '我父母教我', 286, 1, 1),
  ('ket-complete-unit6-students-book-153-synonym-saturday-morning-weekend-aad51cb6', 'synonym', 'ket', 'KET Complete', 'Unit6 Students book', 'Saturday morning', '周六早上', 'weekend', '周末', 287, 1, 1),
  ('ket-complete-unit6-students-book-155-synonym-do-well-in-sports-competiton-win-a-lot-of-prizes-for-football-8b82078f', 'synonym', 'ket', 'KET Complete', 'Unit6 Students book', 'Do well in sports competiton', '在运动比赛表现好', 'win a lot of prizes for football', '足球赢 了很多奖', 288, 1, 1),
  ('ket-complete-unit6-students-book-159-synonym-start-begin-e5742727', 'synonym', 'ket', 'KET Complete', 'Unit6 Students book', 'Start', '开始', 'begin', '开始', 289, 1, 1),
  ('ket-complete-unit6-workbook-163-synonym-arrive-at-get-to-80ef4610', 'synonym', 'ket', 'KET Complete', 'Unit6 workbook', 'Arrive at', '到达', 'get to', '到达', 290, 1, 1),
  ('ket-complete-unit6-workbook-165-synonym-wont-forget-remember-dae3b33b', 'synonym', 'ket', 'KET Complete', 'Unit6 workbook', 'Won’t forget', '不会忘记', 'remember', '记住', 291, 1, 1),
  ('ket-complete-unit6-workbook-167-synonym-chat-to-new-students-meet-new-people-9e22054f', 'synonym', 'ket', 'KET Complete', 'Unit6 workbook', 'Chat to new students', '和新学生聊天', 'meet new people', '认识新的人', 292, 1, 1),
  ('ket-complete-unit6-workbook-169-synonym-left-in-the-forget-to-take-0a228522', 'synonym', 'ket', 'KET Complete', 'Unit6 workbook', 'Left...in the', '把...忘在', 'forget to take', '忘记拿', 293, 1, 1),
  ('ket-complete-unit6-workbook-171-synonym-outside-school-shopping-mall-803f78b7', 'synonym', 'ket', 'KET Complete', 'Unit6 workbook', 'Outside school', '在校外', 'shopping mall', '购物中心', 294, 1, 1),
  ('ket-complete-unit6-workbook-173-synonym-isnt-keen-on-doesnt-like-0a746e8b', 'synonym', 'ket', 'KET Complete', 'Unit6 workbook', 'Isn’t keen on', '不热衷于', 'doesn''t like', '不喜欢', 295, 1, 1),
  ('ket-complete-unit6-workbook-175-synonym-doesnt-talk-much-dont-chat-19a1a16b', 'synonym', 'ket', 'KET Complete', 'Unit6 workbook', 'doesn''t talk much', '不怎么说话', 'don’t chat', '不聊天', 296, 1, 1),
  ('ket-complete-unit7-students-book-179-synonym-special-offer-cheaper-b1fa5813', 'synonym', 'ket', 'KET Complete', 'Unit7 Students book', 'Special offer', '特价', 'cheaper', '更便宜', 297, 1, 1),
  ('ket-complete-unit7-students-book-181-synonym-half-price-cost-50-less-d69409c3', 'synonym', 'ket', 'KET Complete', 'Unit7 Students book', 'Half price', '半价', 'cost 50% less', '花少于 50%的钱', 298, 1, 1),
  ('ket-complete-unit7-students-book-183-synonym-pounds-is-a-lot-20-expensive-681f2f73', 'synonym', 'ket', 'KET Complete', 'Unit7 Students book', 'pounds is a lot 20', '块很多', 'expensive', '贵的', 299, 1, 1),
  ('ket-complete-unit7-students-book-185-synonym-near-the-beach-close-to-the-sea-0a3b6602', 'synonym', 'ket', 'KET Complete', 'Unit7 Students book', 'Near the beach', '在沙滩附近', 'close to the sea', '靠近大海', 300, 1, 1),
  ('ket-complete-unit7-students-book-187-synonym-online-on-the-internet-f295ad66', 'synonym', 'ket', 'KET Complete', 'Unit7 Students book', 'Online', '在网上', 'on the internet', '在网上', 301, 1, 1),
  ('ket-complete-unit7-workbook-191-synonym-staff-only-people-who-work-here-can-use-it-dec5f2f2', 'synonym', 'ket', 'KET Complete', 'Unit7 workbook', 'Staff only', '员工专用', 'people who work here can use it', '在这里工作的人可以使用', 302, 1, 1),
  ('ket-complete-unit7-workbook-193-synonym-check-before-you-come-dont-go-until-youve-checked-286a33d3', 'synonym', 'ket', 'KET Complete', 'Unit7 workbook', 'Check before you come', '来之前检查', 'don’t go until you’ve checked', '在检查之前不要去', 303, 1, 1),
  ('ket-complete-unit7-workbook-195-synonym-like-enjoy-af00c829', 'synonym', 'ket', 'KET Complete', 'Unit7 workbook', 'Like', '喜欢', 'enjoy', '享受', 304, 1, 1),
  ('ket-complete-unit7-workbook-197-synonym-big-bag-heavy-luggage-64b0d2f3', 'synonym', 'ket', 'KET Complete', 'Unit7 workbook', 'Big bag', '大包', 'heavy luggage', '重的行李', 305, 1, 1),
  ('ket-complete-unit7-workbook-199-synonym-havent-got-a-seat-have-to-stand-00cd80a9', 'synonym', 'ket', 'KET Complete', 'Unit7 workbook', 'haven''t got a seat', '没有座位', 'have to stand', '得站着', 306, 1, 1),
  ('ket-complete-unit7-workbook-201-synonym-raining-bad-weather-e5c76268', 'synonym', 'ket', 'KET Complete', 'Unit7 workbook', 'Raining', '下雨', 'bad weather', '不好的天气', 307, 1, 1),
  ('ket-complete-unit8-students-book-205-synonym-funny-make-people-laugh-177eec8f', 'synonym', 'ket', 'KET Complete', 'Unit8 Students book', 'Funny', '搞笑的', 'make people laugh', '使人发笑', 308, 1, 1),
  ('ket-complete-unit8-students-book-207-synonym-a-year-twelve-months-12-0bbee650', 'synonym', 'ket', 'KET Complete', 'Unit8 Students book', 'A year', '一年', 'twelve months 12', '个月', 309, 1, 1),
  ('ket-complete-unit8-students-book-209-synonym-like-helping-people-makes-me-feel-good-to-help-them-6c6ba3c7', 'synonym', 'ket', 'KET Complete', 'Unit8 Students book', 'Like helping people', '喜欢帮助人', 'makes me feel good to help them', '帮助他们让我感受 很好', 310, 1, 1),
  ('ket-complete-unit8-students-book-213-synonym-receive-good-wishes-get-lots-of-nice-messages-4d47fe8f', 'synonym', 'ket', 'KET Complete', 'Unit8 Students book', 'Receive good wishes', '收到好的祝福', 'get lots of nice messages', '收到很多好的消息', 311, 1, 1),
  ('ket-complete-unit8-students-book-215-synonym-post-upload-3b36f6d3', 'synonym', 'ket', 'KET Complete', 'Unit8 Students book', 'Post', '发布', 'upload', '上传', 312, 1, 1),
  ('ket-complete-unit8-students-book-217-synonym-post-more-than-one-video-a-week-upload-a-video-every-three-days-210925da', 'synonym', 'ket', 'KET Complete', 'Unit8 Students book', 'Post more than one video a week', '一周发布超过一个视频', 'upload a video every three days', '每三天上传一个视频', 313, 1, 1),
  ('ket-complete-unit8-students-book-221-synonym-earn-money-from-videos-they-pay-me-to-make-videos-264fad2f', 'synonym', 'ket', 'KET Complete', 'Unit8 Students book', 'Earn money from videos', '从视频里赚钱', 'they pay me to make videos', '他们付钱让我做视 频', 314, 1, 1),
  ('ket-complete-unit8-workbook-227-synonym-play-tennis-and-won-won-a-match-c73dc7a4', 'synonym', 'ket', 'KET Complete', 'Unit8 workbook', 'Play tennis and won', '打网球赢了', 'won a match', '赢了一场比赛', 315, 1, 1),
  ('ket-complete-unit8-workbook-229-synonym-on-her-way-to-the-cinema-she-saw-a-film-35bee1c9', 'synonym', 'ket', 'KET Complete', 'Unit8 workbook', 'On her way to the cinema', '在她去电影院的路上', 'She saw a film', '她看了一场电影', 316, 1, 1),
  ('ket-complete-unit8-workbook-231-synonym-video-game-computer-game-755d5f75', 'synonym', 'ket', 'KET Complete', 'Unit8 workbook', 'Video game', '电子游戏', 'computer game', '电脑游戏', 317, 1, 1),
  ('ket-complete-unit8-workbook-233-synonym-was-taught-how-to-sing-have-singing-lessons-ea2f4eec', 'synonym', 'ket', 'KET Complete', 'Unit8 workbook', 'Was taught how to sing', '被教怎么唱歌', 'have singing lessons', '上唱歌课', 318, 1, 1),
  ('ket-complete-unit8-workbook-235-synonym-with-other-people-in-groups-56f300c7', 'synonym', 'ket', 'KET Complete', 'Unit8 workbook', 'With other people', '和其他人', 'in groups', '在组合里', 319, 1, 1),
  ('ket-complete-unit8-workbook-237-synonym-come-first-win-9f9a0f06', 'synonym', 'ket', 'KET Complete', 'Unit8 workbook', 'Come first', '第一', 'win', '赢', 320, 1, 1),
  ('ket-complete-unit8-workbook-239-synonym-tv-competition-tv-talent-show-8a55da6f', 'synonym', 'ket', 'KET Complete', 'Unit8 workbook', 'TV competition', '电视比赛', 'TV talent show', '电视才艺秀', 321, 1, 1),
  ('ket-complete-unit10-students-book-243-synonym-in-august-in-summer-7e226125', 'synonym', 'ket', 'KET Complete', 'Unit10 Students book', 'In August', '在 8 月', 'in summer', '在夏天', 322, 1, 1),
  ('ket-complete-unit10-students-book-245-synonym-have-to-go-at-3-need-to-leave-at-3-19093e51', 'synonym', 'ket', 'KET Complete', 'Unit10 Students book', 'Have to go at 3', '得 3 点走', 'need to leave at 3', '需要 3 点离开', 323, 1, 1),
  ('ket-complete-unit10-students-book-247-synonym-meet-me-at-the-airport-pick-me-up-at-the-airport-478776b3', 'synonym', 'ket', 'KET Complete', 'Unit10 Students book', 'Meet me at the airport', '来机场见我', 'pick me up at the airport', '来机场接我', 324, 1, 1),
  ('ket-complete-unit10-students-book-249-synonym-after-breakfast-in-the-morning-e7e4eeba', 'synonym', 'ket', 'KET Complete', 'Unit10 Students book', 'After breakfast', '早餐后', 'in the morning', '在早上', 325, 1, 1),
  ('ket-complete-unit10-students-book-251-synonym-at-any-time-of-a-year-all-year-round-fe056d0e', 'synonym', 'ket', 'KET Complete', 'Unit10 Students book', 'At any time of a year', '在一年的任何时候', 'all year round', '一年到头', 326, 1, 1),
  ('ket-complete-unit10-students-book-253-synonym-early-in-the-morning-before-it-got-light-61f0a245', 'synonym', 'ket', 'KET Complete', 'Unit10 Students book', 'Early in the morning', '一大早', 'before it got light', '在天亮前', 327, 1, 1),
  ('ket-complete-unit10-students-book-255-synonym-guide-someone-who-explain-things-9ab04122', 'synonym', 'ket', 'KET Complete', 'Unit10 Students book', 'Guide', '导游', 'someone who explain things', '解释事情的人', 328, 1, 1),
  ('ket-complete-unit10-workbook-259-synonym-cousin-family-member-a2c47a2d', 'synonym', 'ket', 'KET Complete', 'Unit10 workbook', 'Cousin', '堂/表兄弟姐妹', 'family member', '家庭成员', 329, 1, 1),
  ('ket-complete-unit10-workbook-261-synonym-ride-an-animal-on-a-camel-f0e3df1f', 'synonym', 'ket', 'KET Complete', 'Unit10 workbook', 'Ride an animal', '骑动物', 'on a camel', '在骆驼上', 330, 1, 1),
  ('ket-complete-unit10-workbook-263-synonym-wont-be-able-to-wont-have-time-for-58d8b40e', 'synonym', 'ket', 'KET Complete', 'Unit10 workbook', 'Won’t be able to', '不能做', 'won’t have time for', '没有时间做', 331, 1, 1),
  ('ket-complete-unit10-workbook-265-synonym-worry-about-sacred-of-3acf1988', 'synonym', 'ket', 'KET Complete', 'Unit10 workbook', 'Worry about', '担忧', 'sacred of', '害怕', 332, 1, 1),
  ('ket-complete-unit10-workbook-267-synonym-take-warm-clothes-pack-for-cold-weather-2f31a8f0', 'synonym', 'ket', 'KET Complete', 'Unit10 workbook', 'Take warm clothes', '带暖和的衣服', 'pack for cold weather', '为冷的天气打包行李', 333, 1, 1),
  ('ket-complete-unit11-students-book-271-synonym-can-no-longer-be-a-not-possible-to-be-a-72cbcbde', 'synonym', 'ket', 'KET Complete', 'Unit11 Students book', 'Can no longer be a', '不能再当一个', 'not possible to be a', '不可能成为一个', 334, 1, 1),
  ('ket-complete-unit11-students-book-273-synonym-the-time-to-begin-is-now-start-immediately-f826fcf1', 'synonym', 'ket', 'KET Complete', 'Unit11 Students book', 'The time to begin is now', '现在就是开始的时候', 'start immediately', '立即开始', 335, 1, 1),
  ('ket-complete-unit11-students-book-275-synonym-buy-my-own-flat-get-my-own-place-to-live-2fa20975', 'synonym', 'ket', 'KET Complete', 'Unit11 Students book', 'Buy my own flat', '买自己的公寓', 'get my own place to live', '获得属于自己的居住的地方', 336, 1, 1),
  ('ket-complete-unit11-students-book-277-synonym-kicked-my-leg-i-was-hurt-a1ee8a19', 'synonym', 'ket', 'KET Complete', 'Unit11 Students book', 'Kicked my leg', '踢了我的腿', 'I was hurt', '我受伤了', 337, 1, 1),
  ('ket-complete-unit11-students-book-279-synonym-getting-better-at-improving-84cc2269', 'synonym', 'ket', 'KET Complete', 'Unit11 Students book', 'Getting better at', '在...变更好', 'improving', '在进步', 338, 1, 1),
  ('ket-complete-unit11-students-book-281-synonym-get-food-from-the-market-go-shopping-26021455', 'synonym', 'ket', 'KET Complete', 'Unit11 Students book', 'Get food from the market', '从市场获得食物', 'go shopping', '去购物', 339, 1, 1),
  ('ket-complete-unit11-students-book-283-synonym-cant-move-legs-legs-are-tired-12206957', 'synonym', 'ket', 'KET Complete', 'Unit11 Students book', 'Can’t move legs', '腿不能动了', 'legs are tired', '腿很累', 340, 1, 1),
  ('ket-complete-unit11-workbook-287-synonym-his-parents-are-very-busy-in-their-shop-his-family-has-a-small-business-7409bb86', 'synonym', 'ket', 'KET Complete', 'Unit11 workbook', 'His parents are very busy in their shop', '他 的 父 母 在 店 里 很 忙', 'His family has a small business', '他的家人有一个小生意', 341, 1, 1),
  ('ket-complete-unit11-workbook-291-synonym-cant-move-my-fingers-my-hand-hurt-825247ea', 'synonym', 'ket', 'KET Complete', 'Unit11 workbook', 'Can’t move my fingers', '手指动不了', 'my hand hurt', '我的手受伤了', 342, 1, 1),
  ('ket-complete-unit11-workbook-293-synonym-the-sky-is-grey-it-is-cloudy-6462191a', 'synonym', 'ket', 'KET Complete', 'Unit11 workbook', 'The sky is grey', '天是灰色的', 'it is cloudy', '多云天', 343, 1, 1),
  ('ket-complete-unit11-workbook-295-synonym-laugh-at-the-beginning-some-parts-are-funny-2cb6d814', 'synonym', 'ket', 'KET Complete', 'Unit11 workbook', 'Laugh at the beginning', '在开始的时候笑了', 'some parts are funny', '有些部分很搞笑', 344, 1, 1),
  ('ket-complete-unit12-students-book-299-synonym-half-price-for-groups-of-10-or-more-10-you-will-pay-more-do-do-this-alone-49928213', 'synonym', 'ket', 'KET Complete', 'Unit12 Students book', 'half price for groups of 10 or more 10', '人或以上的组半价', 'you will pay more do do this alone', '你独自一人做这个会要付更多钱', 345, 1, 1),
  ('ket-complete-unit12-students-book-303-synonym-or-nearest-offer-10-the-price-can-be-changed-3e99698a', 'synonym', 'ket', 'KET Complete', 'Unit12 Students book', 'or nearest offer 10', '快或最接近 10 块的价格', 'the price can be changed', '价格可以改变', 346, 1, 1),
  ('ket-complete-unit12-students-book-305-synonym-tell-talk-to-5c38252f', 'synonym', 'ket', 'KET Complete', 'Unit12 Students book', 'tell', '告诉', 'talk to', '和...说', 347, 1, 1),
  ('ket-complete-unit12-students-book-307-synonym-friendly-staff-nice-people-working-there-90014837', 'synonym', 'ket', 'KET Complete', 'Unit12 Students book', 'Friendly staff', '友好的员工', 'nice people working there', '在那工作的人都很好', 348, 1, 1),
  ('ket-complete-unit12-students-book-309-synonym-beginner-havent-done-it-before-1bffb013', 'synonym', 'ket', 'KET Complete', 'Unit12 Students book', 'beginner', '初学者', 'haven’t done it before', '之前没有做过', 349, 1, 1),
  ('ket-complete-unit12-workbook-313-synonym-win-have-a-competition-6f3204ae', 'synonym', 'ket', 'KET Complete', 'Unit12 workbook', 'win', '赢得', 'have a competition', '举办比赛', 350, 1, 1),
  ('ket-complete-unit12-workbook-315-synonym-get-off-your-bike-you-shouldnt-ride-your-bike-148b3959', 'synonym', 'ket', 'KET Complete', 'Unit12 workbook', 'get off your bike', '下自行车', 'you shouldn''t ride your bike', '你不应该骑自行车', 351, 1, 1),
  ('ket-complete-unit12-workbook-317-synonym-cash-only-you-cant-pay-by-credit-card-16df6d65', 'synonym', 'ket', 'KET Complete', 'Unit12 workbook', 'cash only', '只收现金', 'you can’t pay by credit card', '你不能用信用卡支付', 352, 1, 1),
  ('ket-complete-unit12-workbook-319-synonym-under-18s-half-price-its-cheaper-for-under-18s-51b39749', 'synonym', 'ket', 'KET Complete', 'Unit12 workbook', 'Under-18s half price', '低于 18 岁半价', 'It’s cheaper for under-18s', '低于 18 岁便宜些', 353, 1, 1),
  ('ket-complete-unit13-students-book-323-synonym-this-morning-earlier-today-5407ff2f', 'synonym', 'ket', 'KET Complete', 'Unit13 Students book', 'this morning', '今天早上', 'earlier today', '今天早些时候', 354, 1, 1),
  ('ket-complete-unit13-students-book-325-synonym-i-hope-it-will-be-more-interesting-next-time-this-time-is-a-bit-boring-bb10782d', 'synonym', 'ket', 'KET Complete', 'Unit13 Students book', 'I hope it will be more interesting next time', '我希望下次会更有趣', 'this time is a bit boring', '这次有一点无聊', 355, 1, 1),
  ('ket-complete-unit13-students-book-329-synonym-won-a-lot-of-prizes-for-horse-riding-an-excellent-rider-b95dfd77', 'synonym', 'ket', 'KET Complete', 'Unit13 Students book', 'Won a lot of prizes for horse riding', '骑马赢了很多奖', 'an excellent rider', '一个很棒的骑手', 356, 1, 1),
  ('ket-complete-unit13-students-book-331-synonym-teacher-at-school-19ef6012', 'synonym', 'ket', 'KET Complete', 'Unit13 Students book', 'teacher', '老师', 'at school', '在学校', 357, 1, 1),
  ('ket-complete-unit13-students-book-333-synonym-meet-lots-of-lovely-people-make-new-friends-264ed193', 'synonym', 'ket', 'KET Complete', 'Unit13 Students book', 'Meet lots of lovely people', '见很多可爱的人', 'make new friends', '交新朋友', 358, 1, 1),
  ('ket-complete-unit13-students-book-335-synonym-funny-stuff-comedy-513c3ba3', 'synonym', 'ket', 'KET Complete', 'Unit13 Students book', 'funny stuff', '有趣的东西', 'comedy', '喜剧', 359, 1, 1),
  ('ket-complete-unit13-workbook-339-synonym-new-clothes-for-snowboarding-something-to-wear-to-do-sports-1f7bce1a', 'synonym', 'ket', 'KET Complete', 'Unit13 workbook', 'New clothes for snowboarding', '滑板滑雪的新衣服', 'something to wear to do sports', '为 了做运动的衣物', 360, 1, 1),
  ('ket-complete-unit13-workbook-343-synonym-isnt-safe-dangerous-015a1447', 'synonym', 'ket', 'KET Complete', 'Unit13 workbook', 'isn''t safe', '不安全', 'dangerous', '危险的', 361, 1, 1),
  ('ket-complete-unit13-workbook-345-synonym-earn-money-by-somebody-pay-to-258ba0f3', 'synonym', 'ket', 'KET Complete', 'Unit13 workbook', 'earn money by', '通过...赚钱', 'somebody pay ...to', '有人付钱让..做', 362, 1, 1),
  ('ket-complete-unit13-workbook-347-synonym-several-times-more-than-once-6c379965', 'synonym', 'ket', 'KET Complete', 'Unit13 workbook', 'several times', '几次', 'more than once', '超过一次', 363, 1, 1),
  ('ket-complete-unit13-workbook-349-synonym-most-of-the-time-almost-slways-86b3e8bf', 'synonym', 'ket', 'KET Complete', 'Unit13 workbook', 'most of the time', '大多数时候', 'almost slways', '几乎总是', 364, 1, 1),
  ('ket-complete-unit14-students-book-353-synonym-modern-very-21st-century-865233d9', 'synonym', 'ket', 'KET Complete', 'Unit14 Students book', 'modern', '现代化的', 'very 21st century', '非常 21 世纪', 365, 1, 1),
  ('ket-complete-unit14-students-book-355-synonym-clear-easy-to-understand-708e824f', 'synonym', 'ket', 'KET Complete', 'Unit14 Students book', 'clear', '清晰的', 'easy to understand', '容易理解', 366, 1, 1),
  ('ket-complete-unit14-students-book-357-synonym-funny-tell-jokes-00ffdc97', 'synonym', 'ket', 'KET Complete', 'Unit14 Students book', 'funny', '搞笑的', 'tell jokes', '讲笑话', 367, 1, 1),
  ('ket-complete-unit14-students-book-359-synonym-slow-it-took-a-long-time-30bbbf35', 'synonym', 'ket', 'KET Complete', 'Unit14 Students book', 'slow', '慢的', 'it took a long time', '花很久时间', 368, 1, 1),
  ('ket-complete-unit14-students-book-361-synonym-bad-terrible-1dd5c276', 'synonym', 'ket', 'KET Complete', 'Unit14 Students book', 'bad', '坏的，不好的', 'terrible', '糟糕的', 369, 1, 1),
  ('ket-complete-unit14-students-book-363-synonym-dark-not-bright-bb7c3630', 'synonym', 'ket', 'KET Complete', 'Unit14 Students book', 'dark', '黑暗的', 'not bright', '不亮', 370, 1, 1),
  ('ket-complete-unit14-workbook-367-synonym-leave-message-on-paper-note-19518844', 'synonym', 'ket', 'KET Complete', 'Unit14 workbook', 'Leave message on paper', '在纸上留信息', 'note', '便条', 371, 1, 1)
ON DUPLICATE KEY UPDATE
  mode = VALUES(mode), level_code = VALUES(level_code), source = VALUES(source), section_name = VALUES(section_name), left_text = VALUES(left_text), left_cn = VALUES(left_cn), right_text = VALUES(right_text), right_cn = VALUES(right_cn), sort = VALUES(sort), status = VALUES(status);

