-- yudao-module-member 核心表：member_user
-- 来自 yudao-module-member/src/test/resources/sql/create_tables.sql，转 MySQL 方言
CREATE TABLE IF NOT EXISTS `member_user` (
    `id`                BIGINT       NOT NULL AUTO_INCREMENT COMMENT '编号',
    `nickname`          VARCHAR(30)  NOT NULL DEFAULT '' COMMENT '用户昵称',
    `name`              VARCHAR(30)  DEFAULT NULL COMMENT '真实名字',
    `sex`               TINYINT      DEFAULT NULL COMMENT '性别',
    `birthday`          DATETIME     DEFAULT NULL COMMENT '出生日期',
    `area_id`           INT          DEFAULT NULL COMMENT '所在地',
    `mark`              VARCHAR(255) DEFAULT NULL COMMENT '用户备注',
    `point`             INT          DEFAULT 0 COMMENT '积分',
    `avatar`            VARCHAR(255) NOT NULL DEFAULT '' COMMENT '头像',
    `status`            TINYINT      NOT NULL DEFAULT 0 COMMENT '状态 0=启用 1=停用',
    `mobile`            VARCHAR(11)  DEFAULT '' COMMENT '手机号',
    `password`          VARCHAR(100) NOT NULL DEFAULT '' COMMENT '密码',
    `register_ip`       VARCHAR(32)  NOT NULL DEFAULT '' COMMENT '注册 IP',
    `register_terminal` INT          DEFAULT NULL COMMENT '注册终端',
    `login_ip`          VARCHAR(50)  DEFAULT '' COMMENT '最后登录IP',
    `login_date`        DATETIME     DEFAULT NULL COMMENT '最后登录时间',
    `tag_ids`           VARCHAR(255) DEFAULT NULL COMMENT '用户标签编号列表,以逗号分隔',
    `level_id`          BIGINT       DEFAULT NULL COMMENT '等级编号',
    `experience`        BIGINT       DEFAULT NULL COMMENT '经验',
    `group_id`          BIGINT       DEFAULT NULL COMMENT '用户分组编号',
    `creator`           VARCHAR(64)  DEFAULT '' COMMENT '创建者',
    `create_time`       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater`           VARCHAR(64)  DEFAULT '' COMMENT '更新者',
    `update_time`       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted`           BIT(1)       NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id`         BIGINT       NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_mobile` (`mobile`, `deleted`),
    KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员表';
