-- KET expression practice extracted and editorially cleaned from
-- Complete Key for Schools 2nd Student's Book, Speaking sections.

CREATE TABLE IF NOT EXISTS esc_expression_dialogue_task (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    code        VARCHAR(64)  NOT NULL COMMENT 'Stable task code',
    level_code  VARCHAR(32)  NOT NULL DEFAULT 'ket',
    title_cn    VARCHAR(100) NOT NULL,
    title_en    VARCHAR(100) NOT NULL,
    topic_code  VARCHAR(48)  NOT NULL,
    prompt_en   VARCHAR(500) NOT NULL,
    prompt_cn   VARCHAR(500) DEFAULT '',
    config_json LONGTEXT     NOT NULL COMMENT 'Roles, image slots, language support and source',
    sort        INT          NOT NULL DEFAULT 0,
    status      TINYINT      NOT NULL DEFAULT 1 COMMENT '0 draft, 1 published, 2 archived',
    tenant_id   BIGINT       NOT NULL DEFAULT 0,
    creator     VARCHAR(64)  DEFAULT '',
    create_time DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater     VARCHAR(64)  DEFAULT '',
    update_time DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted     BIT(1)       NOT NULL DEFAULT 0,
    UNIQUE KEY uk_expression_dialogue_code (tenant_id, level_code, code, deleted),
    INDEX idx_expression_dialogue_level (level_code, status, sort)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='KET Part 2 role-based dialogue tasks';

CREATE TABLE IF NOT EXISTS esc_expression_dialogue_attempt (
    id               BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id          BIGINT      NOT NULL,
    task_id          BIGINT      NOT NULL,
    selected_role    VARCHAR(16) NOT NULL COMMENT 'student_a/student_b',
    transcript_json  LONGTEXT    NOT NULL,
    score            INT         NOT NULL DEFAULT 0,
    feedback_json    LONGTEXT    DEFAULT NULL,
    duration_seconds INT         DEFAULT NULL,
    tenant_id        BIGINT      NOT NULL DEFAULT 0,
    creator          VARCHAR(64) DEFAULT '',
    create_time      DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater          VARCHAR(64) DEFAULT '',
    update_time      DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted          BIT(1)      NOT NULL DEFAULT 0,
    INDEX idx_expression_dialogue_attempt_user (user_id, create_time),
    INDEX idx_expression_dialogue_attempt_task (task_id, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='KET Part 2 dialogue attempts';

INSERT IGNORE INTO esc_expression_theme
    (code, name_cn, name_en, description, level_code, sort, status, tenant_id)
VALUES
    ('personal-life', '个人信息与日常', 'Personal Life', '练习自我介绍、周末安排和日常习惯。', 'ket', 20, 1, 1),
    ('school-learning', '学校与学习', 'School and Learning', '谈论学校、老师和喜欢的科目。', 'ket', 30, 1, 1),
    ('shopping-clothes', '购物与服装', 'Shopping and Clothes', '谈论购物地点、同伴和喜欢的服装。', 'ket', 40, 1, 1),
    ('home-family', '家庭与住房', 'Home and Family', '介绍家人、住房和自己的房间。', 'ket', 50, 1, 1),
    ('sports-leisure', '运动与休闲', 'Sports and Leisure', '谈论运动、兴趣和休闲活动。', 'ket', 60, 1, 1);

SET @ket_personal_theme := (SELECT id FROM esc_expression_theme WHERE code='personal-life' AND level_code='ket' AND tenant_id=1 AND deleted=b'0' ORDER BY id LIMIT 1);
SET @ket_school_theme := (SELECT id FROM esc_expression_theme WHERE code='school-learning' AND level_code='ket' AND tenant_id=1 AND deleted=b'0' ORDER BY id LIMIT 1);
SET @ket_shopping_theme := (SELECT id FROM esc_expression_theme WHERE code='shopping-clothes' AND level_code='ket' AND tenant_id=1 AND deleted=b'0' ORDER BY id LIMIT 1);
SET @ket_home_theme := (SELECT id FROM esc_expression_theme WHERE code='home-family' AND level_code='ket' AND tenant_id=1 AND deleted=b'0' ORDER BY id LIMIT 1);
SET @ket_sports_theme := (SELECT id FROM esc_expression_theme WHERE code='sports-leisure' AND level_code='ket' AND tenant_id=1 AND deleted=b'0' ORDER BY id LIMIT 1);
SET @ket_food_theme := (SELECT id FROM esc_expression_theme WHERE code='food-drink' AND level_code='ket' AND tenant_id=1 AND deleted=b'0' ORDER BY id LIMIT 1);

INSERT IGNORE INTO esc_expression_item
    (theme_id, code, prompt_en, prompt_cn, function_code, practice_mode, difficulty, answer_json, sort, status, tenant_id)
VALUES
(@ket_personal_theme, 'ckfs2-p1-name', 'What''s your name?', '你叫什么名字？', 'give-personal-information', 'speaking', 1,
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":148,"examPart":1,"status":"reviewed"},"answers":{"basic":{"en":"My name is Alex.","cn":"我叫Alex。"},"expanded":{"en":"My name is Alex, but my friends call me Al.","cn":"我叫Alex，不过朋友们叫我Al。"}},"patterns":[{"en":"My name is ___.","cn":"我叫___。","slots":{"name":["Alex","Sam","Charlie"]}}],"keywords":["my name is"]}', 10, 1, 1),
(@ket_personal_theme, 'ckfs2-p1-weekends', 'What do you usually do at weekends?', '你周末通常做什么？', 'describe-routine', 'speaking', 1,
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":148,"examPart":1,"status":"reviewed"},"answers":{"basic":{"en":"I usually play basketball at weekends.","cn":"我周末通常打篮球。"},"expanded":{"en":"I usually play basketball with my friends and watch films with my family.","cn":"我通常和朋友打篮球，也会和家人看电影。"}},"patterns":[{"en":"I usually ___ at weekends because ___.","cn":"周末我通常___，因为___。","slots":{"activity":["play sport","meet my friends","watch films"],"reason":["it is fun","I can relax","I enjoy it"]}}],"keywords":["usually","at weekends"]}', 20, 1, 1),
(@ket_personal_theme, 'ckfs2-p1-weekend-company', 'Who do you like spending your weekends with?', '你喜欢和谁一起过周末？', 'describe-preference', 'speaking', 1,
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":147,"examPart":1,"status":"reviewed"},"answers":{"basic":{"en":"I like spending my weekends with my friends.","cn":"我喜欢和朋友一起过周末。"},"expanded":{"en":"I like spending my weekends with my friends because we enjoy playing football together.","cn":"我喜欢和朋友一起过周末，因为我们喜欢一起踢足球。"}},"patterns":[{"en":"I like spending my weekends with ___ because ___.","cn":"我喜欢和___一起过周末，因为___。","slots":{"person":["my friends","my family","my cousins"],"reason":["we have fun together","we like the same things"]}}],"keywords":["with","because"]}', 30, 1, 1),
(@ket_personal_theme, 'ckfs2-p1-meet-friends', 'Where do you usually meet your friends?', '你通常在哪里见朋友？', 'describe-routine', 'speaking', 1,
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":148,"examPart":1,"status":"reviewed"},"answers":{"basic":{"en":"I usually meet my friends at the park.","cn":"我通常在公园见朋友。"},"expanded":{"en":"I usually meet my friends at the park after school, and we play basketball there.","cn":"放学后我通常在公园见朋友，我们会在那里打篮球。"}},"patterns":[{"en":"I usually meet my friends at ___, and we ___.","cn":"我通常在___见朋友，我们会___。","slots":{"place":["the park","the cinema","the sports centre"],"activity":["talk","play sport","have something to eat"]}}],"keywords":["usually","meet"]}', 40, 1, 1),
(@ket_school_theme, 'ckfs2-p1-school', 'Please tell me something about your school.', '请介绍一下你的学校。', 'describe-place', 'speaking', 2,
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":20,"examPart":1,"status":"reviewed"},"answers":{"basic":{"en":"My school is big. It has a sports field and a library.","cn":"我的学校很大，有运动场和图书馆。"},"expanded":{"en":"My school is quite big. It has a library and a sports field, and I like my classmates.","cn":"我的学校很大，有图书馆和运动场，我也喜欢我的同学。"}},"patterns":[{"en":"My school is ___. It has ___, and I like ___.","cn":"我的学校很___。它有___，我喜欢___。","slots":{"size":["big","small","modern"],"facility":["a library","a sports field","a music room"],"feature":["my classmates","the teachers","the lessons"]}}],"keywords":["school","it has"]}', 10, 1, 1),
(@ket_school_theme, 'ckfs2-p1-english-teacher', 'Please tell me something about your English teacher.', '请介绍一下你的英语老师。', 'describe-person', 'speaking', 2,
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":20,"examPart":1,"status":"reviewed"},"answers":{"basic":{"en":"My English teacher is friendly and helpful.","cn":"我的英语老师友好而且乐于助人。"},"expanded":{"en":"My English teacher is friendly and helpful. The lessons are interesting because we play language games.","cn":"我的英语老师友好又乐于助人。课堂很有趣，因为我们会玩语言游戏。"}},"patterns":[{"en":"My English teacher is ___ and ___. In class, we ___.","cn":"我的英语老师___而且___。课堂上我们___。","slots":{"quality":["friendly","helpful","funny"],"activity":["play language games","read stories","practise speaking"]}}],"keywords":["teacher","friendly"]}', 20, 1, 1),
(@ket_school_theme, 'ckfs2-p2-favourite-subject', 'What''s your favourite school subject?', '你最喜欢什么科目？', 'give-preference', 'speaking', 1,
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":48,"examPart":2,"phase":2,"status":"reviewed"},"answers":{"basic":{"en":"My favourite subject is science.","cn":"我最喜欢科学。"},"expanded":{"en":"My favourite subject is science because I like learning about the world.","cn":"我最喜欢科学，因为我喜欢了解世界。"}},"patterns":[{"en":"My favourite subject is ___ because ___.","cn":"我最喜欢___，因为___。","slots":{"subject":["science","English","art"],"reason":["it is interesting","I enjoy the lessons","I am good at it"]}}],"keywords":["favourite subject","because"]}', 30, 1, 1),
(@ket_school_theme, 'ckfs2-p2-science-or-arts', 'Do you prefer studying science or arts subjects?', '你更喜欢理科还是文科/艺术类科目？', 'compare-preferences', 'speaking', 2,
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":48,"examPart":2,"phase":2,"status":"reviewed"},"answers":{"basic":{"en":"I prefer science subjects.","cn":"我更喜欢理科。"},"expanded":{"en":"I prefer science subjects because I enjoy doing experiments, but I like art too.","cn":"我更喜欢理科，因为我喜欢做实验，不过我也喜欢美术。"}},"patterns":[{"en":"I prefer ___ because ___, but ___.","cn":"我更喜欢___，因为___，不过___。","slots":{"choice":["science subjects","arts subjects"],"reason":["they are interesting","I enjoy the lessons"],"contrast":["I like both","the other subjects are useful too"]}}],"keywords":["prefer","because","but"]}', 40, 1, 1),
(@ket_shopping_theme, 'ckfs2-p1-shopping-place', 'Where do you like going shopping?', '你喜欢去哪里购物？', 'describe-preference', 'speaking', 1,
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":147,"examPart":1,"status":"reviewed"},"answers":{"basic":{"en":"I like going shopping in the town centre.","cn":"我喜欢去市中心购物。"},"expanded":{"en":"I like going shopping in the town centre because there are lots of different shops.","cn":"我喜欢去市中心购物，因为那里有很多不同的商店。"}},"patterns":[{"en":"I like going shopping at ___ because ___.","cn":"我喜欢去___购物，因为___。","slots":{"place":["the shopping centre","the market","the town centre"],"reason":["there are lots of shops","it is near my home","prices are good"]}}],"keywords":["shopping","because"]}', 10, 1, 1),
(@ket_shopping_theme, 'ckfs2-p1-shopping-company', 'Who do you like going shopping with?', '你喜欢和谁一起购物？', 'describe-preference', 'speaking', 1,
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":148,"examPart":1,"status":"reviewed"},"answers":{"basic":{"en":"I like going shopping with my mum.","cn":"我喜欢和妈妈一起购物。"},"expanded":{"en":"I like going shopping with my mum because she helps me choose clothes.","cn":"我喜欢和妈妈购物，因为她会帮我挑衣服。"}},"patterns":[{"en":"I like going shopping with ___ because ___.","cn":"我喜欢和___购物，因为___。","slots":{"person":["my mum","my friends","my sister"],"reason":["we like the same things","they help me choose","it is more fun"]}}],"keywords":["with","because"]}', 20, 1, 1),
(@ket_shopping_theme, 'ckfs2-p1-buying', 'What do you like buying?', '你喜欢买什么？', 'give-preference', 'speaking', 1,
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":147,"examPart":1,"status":"reviewed"},"answers":{"basic":{"en":"I like buying books.","cn":"我喜欢买书。"},"expanded":{"en":"I like buying books and sports clothes because I use them a lot.","cn":"我喜欢买书和运动服，因为我经常用到它们。"}},"patterns":[{"en":"I like buying ___ because ___.","cn":"我喜欢买___，因为___。","slots":{"item":["books","clothes","games"],"reason":["I use them a lot","they are interesting","I enjoy them"]}}],"keywords":["like buying","because"]}', 30, 1, 1),
(@ket_shopping_theme, 'ckfs2-p1-clothes', 'Tell me something about the clothes you like to buy.', '介绍一下你喜欢买的衣服。', 'describe-preference', 'speaking', 2,
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":148,"examPart":1,"status":"reviewed"},"answers":{"basic":{"en":"I like buying jeans and T-shirts.","cn":"我喜欢买牛仔裤和T恤。"},"expanded":{"en":"I like buying comfortable jeans and colourful T-shirts because I can wear them at weekends.","cn":"我喜欢买舒适的牛仔裤和彩色T恤，因为周末可以穿。"}},"patterns":[{"en":"I like buying ___ because ___. I usually wear them ___.","cn":"我喜欢买___，因为___。我通常在___穿。","slots":{"clothes":["jeans","T-shirts","sports clothes"],"reason":["they are comfortable","I like the colours","they are practical"],"occasion":["at weekends","after school","when I play sport"]}}],"keywords":["clothes","comfortable"]}', 40, 1, 1),
(@ket_home_theme, 'ckfs2-p1-live-with', 'Who do you live with?', '你和谁住在一起？', 'give-personal-information', 'speaking', 1,
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":147,"examPart":1,"status":"reviewed"},"answers":{"basic":{"en":"I live with my parents and my sister.","cn":"我和父母及妹妹住在一起。"},"expanded":{"en":"I live with my parents and my younger sister in a flat near my school.","cn":"我和父母及妹妹住在学校附近的一套公寓里。"}},"patterns":[{"en":"I live with ___ in ___.","cn":"我和___住在___。","slots":{"people":["my parents","my family","my parents and my sister"],"home":["a flat","a house","the town centre"]}}],"keywords":["live with"]}', 10, 1, 1),
(@ket_home_theme, 'ckfs2-p1-home-rooms', 'How many rooms are there in your house or flat?', '你的房子或公寓有几个房间？', 'describe-home', 'speaking', 1,
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":147,"examPart":1,"status":"reviewed"},"answers":{"basic":{"en":"There are six rooms in my flat.","cn":"我的公寓有六个房间。"},"expanded":{"en":"There are six rooms: two bedrooms, a kitchen, a living room and two bathrooms.","cn":"一共有六个房间：两间卧室、厨房、客厅和两间浴室。"}},"patterns":[{"en":"There are ___ rooms: ___.","cn":"有___个房间：___。","slots":{"number":["five","six","seven"],"rooms":["two bedrooms, a kitchen and a living room","three bedrooms and a large kitchen"]}}],"keywords":["there are","rooms"]}', 20, 1, 1),
(@ket_home_theme, 'ckfs2-p1-bedroom', 'Please tell me something about your bedroom.', '请介绍一下你的卧室。', 'describe-home', 'speaking', 2,
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":147,"examPart":1,"status":"reviewed"},"answers":{"basic":{"en":"My bedroom is small but comfortable.","cn":"我的卧室不大但很舒适。"},"expanded":{"en":"My bedroom is small but comfortable. It has a desk by the window and posters on the wall.","cn":"我的卧室不大但很舒适。窗边有书桌，墙上有海报。"}},"patterns":[{"en":"My bedroom is ___. It has ___, and I like ___.","cn":"我的卧室很___。里面有___，我喜欢___。","slots":{"quality":["small but comfortable","bright","quite big"],"feature":["a desk by the window","a big bookshelf","posters on the wall"],"favourite":["reading there","the view","my desk"]}}],"keywords":["bedroom","it has"]}', 30, 1, 1),
(@ket_sports_theme, 'ckfs2-p1-sports-area', 'What sports can you do in your area?', '你住的地方可以做什么运动？', 'describe-local-area', 'speaking', 1,
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":147,"examPart":1,"status":"reviewed"},"answers":{"basic":{"en":"You can play football and tennis in my area.","cn":"我住的地方可以踢足球和打网球。"},"expanded":{"en":"You can play football at the park and go swimming at the sports centre near my home.","cn":"可以在公园踢足球，也可以去我家附近的体育中心游泳。"}},"patterns":[{"en":"You can ___ at ___ in my area.","cn":"在我住的地方可以在___做___。","slots":{"sport":["play football","go swimming","play tennis"],"place":["the park","the sports centre","my school"]}}],"keywords":["can","in my area"]}', 10, 1, 1),
(@ket_sports_theme, 'ckfs2-p1-sports-like', 'Tell me something about the sports you like to do.', '介绍一下你喜欢的运动。', 'describe-preference', 'speaking', 2,
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":148,"examPart":1,"status":"reviewed"},"answers":{"basic":{"en":"I like playing football.","cn":"我喜欢踢足球。"},"expanded":{"en":"I like playing football. I play for a school team, and we have a game every Saturday.","cn":"我喜欢踢足球。我在校队踢球，每周六都有比赛。"}},"patterns":[{"en":"I like ___. I ___, and ___.","cn":"我喜欢___。我___，而且___。","slots":{"sport":["playing football","swimming","playing tennis"],"habit":["practise twice a week","play with my friends","go at weekends"],"detail":["it keeps me fit","it is exciting","we have fun"]}}],"keywords":["I like","every week"]}', 20, 1, 1),
(@ket_food_theme, 'ckfs2-p1-breakfast', 'What did you eat for breakfast this morning?', '你今天早饭吃了什么？', 'describe-past-event', 'speaking', 1,
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":148,"examPart":1,"status":"reviewed"},"answers":{"basic":{"en":"I had cereal and milk.","cn":"我吃了麦片和牛奶。"},"expanded":{"en":"I had cereal, some fruit and a glass of milk for breakfast this morning.","cn":"今天早饭我吃了麦片、水果，还喝了一杯牛奶。"}},"patterns":[{"en":"I had ___ and ___ for breakfast this morning.","cn":"今天早饭我吃了___和___。","slots":{"food":["cereal","eggs","toast"],"drink":["milk","orange juice","water"]}}],"keywords":["had","for breakfast"]}', 70, 1, 1),
(@ket_food_theme, 'ckfs2-p1-eat-with-friends', 'Tell me something about what you like to eat with friends.', '介绍一下你和朋友在一起喜欢吃什么。', 'describe-preference', 'speaking', 2,
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":147,"examPart":1,"status":"reviewed"},"answers":{"basic":{"en":"I like eating pizza with my friends.","cn":"我喜欢和朋友一起吃披萨。"},"expanded":{"en":"I sometimes go to a restaurant with my friends, and we like sharing pizza or noodles.","cn":"我有时和朋友去餐厅，我们喜欢一起吃披萨或面条。"}},"patterns":[{"en":"I like eating ___ with my friends because ___.","cn":"我喜欢和朋友一起吃___，因为___。","slots":{"food":["pizza","noodles","snacks"],"reason":["we can share it","it is delicious","everyone likes it"]}}],"keywords":["with my friends","because"]}', 80, 1, 1);

INSERT IGNORE INTO esc_expression_dialogue_task
    (code, level_code, title_cn, title_en, topic_code, prompt_en, prompt_cn, config_json, sort, status, tenant_id)
VALUES
('ckfs2-p2-eating-places', 'ket', '不同的用餐地点', 'Different places to eat', 'food-drink',
 'Do you like eating in these different places? Say why or why not.', '你喜欢在这些不同的地方吃饭吗？说明原因。',
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":28,"unit":3,"examPart":2,"status":"reviewed"},"starterRole":"student_a","minLearnerTurns":3,"maxTotalTurns":8,"imageSlots":[{"key":"beach","label":"beach","imageUrl":""},{"key":"home","label":"home","imageUrl":""},{"key":"fast-food-place","label":"fast food place","imageUrl":""},{"key":"restaurant","label":"restaurant","imageUrl":""},{"key":"school","label":"school","imageUrl":""}],"targetLanguage":["Do you like ...?","Why? / Why not?","What do you think?","I prefer ... because ..."],"followUpQuestions":["Which place do you like best?","Do you prefer eating at home or in a restaurant?"],"sampleExchange":[{"role":"student_a","text":"Do you like eating in restaurants?"},{"role":"student_b","text":"Yes, because there are different kinds of food. What do you think?"}]}', 10, 1, 1),
('ckfs2-p2-sports', 'ket', '不同的运动', 'Different sports', 'sports-leisure',
 'Do you like these different sports? Say why or why not.', '你喜欢这些不同的运动吗？说明原因。',
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":42,"unit":5,"examPart":2,"status":"reviewed"},"starterRole":"student_a","minLearnerTurns":3,"maxTotalTurns":8,"imageSlots":[{"key":"badminton","label":"badminton","imageUrl":""},{"key":"baseball","label":"baseball","imageUrl":""},{"key":"fishing","label":"fishing","imageUrl":""},{"key":"golf","label":"golf","imageUrl":""},{"key":"rugby","label":"rugby","imageUrl":""},{"key":"skiing","label":"skiing","imageUrl":""},{"key":"surfing","label":"surfing","imageUrl":""}],"targetLanguage":["I really like ...","I have never tried ...","Do you think ... is exciting?","What about you?"],"followUpQuestions":["Which sport would you most like to try?","Do you prefer team sports or individual sports?"],"sampleExchange":[{"role":"student_a","text":"Do you think surfing is exciting?"},{"role":"student_b","text":"Yes, but it looks difficult. I would like to try badminton. What about you?"}]}', 20, 1, 1),
('ckfs2-p2-places', 'ket', '休闲游览地点', 'Places to visit', 'places',
 'Talk about these different places. Say why you like or do not like them.', '讨论这些不同的地点，说明喜欢或不喜欢的原因。',
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":56,"unit":7,"examPart":2,"status":"reviewed"},"starterRole":"student_a","minLearnerTurns":3,"maxTotalTurns":8,"imageSlots":[{"key":"museum","label":"museum","imageUrl":""},{"key":"beach","label":"beach","imageUrl":""},{"key":"castle","label":"castle","imageUrl":""},{"key":"cinema","label":"cinema","imageUrl":""},{"key":"park","label":"park","imageUrl":""}],"targetLanguage":["I like going to ... because ...","The reason I like ... is that ...","Why? / Why not?","What do you think?"],"followUpQuestions":["Which place would you choose for a day out?","Do you prefer indoor or outdoor places?"],"sampleExchange":[{"role":"student_a","text":"I like going to museums because I am interested in history. What do you think?"},{"role":"student_b","text":"I prefer the beach because I enjoy swimming."}]}', 30, 1, 1),
('ckfs2-p2-healthy-activities', 'ket', '健康活动', 'Healthy activities', 'health-fitness',
 'Do you like these healthy activities? Say why or why not.', '你喜欢这些健康活动吗？说明原因。',
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":84,"unit":11,"examPart":2,"status":"reviewed"},"starterRole":"student_a","minLearnerTurns":3,"maxTotalTurns":8,"imageSlots":[{"key":"running","label":"running","imageUrl":""},{"key":"cycling","label":"cycling","imageUrl":""},{"key":"vegetables","label":"eating vegetables","imageUrl":""},{"key":"sleep","label":"getting enough sleep","imageUrl":""},{"key":"swimming","label":"swimming","imageUrl":""}],"targetLanguage":["Do you ... a lot?","How often do you ...?","I think ... is healthy because ...","What about you?"],"followUpQuestions":["Which activity is best for keeping fit?","What healthy activity do you do every week?"],"sampleExchange":[{"role":"student_a","text":"Do you go running very often?"},{"role":"student_b","text":"Not often, but I go cycling every weekend. What about you?"}]}', 40, 1, 1),
('ckfs2-p2-hobbies', 'ket', '不同的兴趣爱好', 'Different hobbies', 'hobbies',
 'Do you like these different hobbies? Say why or why not.', '你喜欢这些不同的兴趣爱好吗？说明原因。',
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":148,"section":"Speaking bank","examPart":2,"status":"reviewed"},"starterRole":"student_a","minLearnerTurns":3,"maxTotalTurns":8,"imageSlots":[{"key":"video-games","label":"playing video games","imageUrl":""},{"key":"photos","label":"taking photos","imageUrl":""},{"key":"cycling","label":"cycling","imageUrl":""},{"key":"instrument","label":"playing an instrument","imageUrl":""},{"key":"team-sports","label":"playing team sports","imageUrl":""}],"targetLanguage":["I think ... is exciting.","I am not sure about that.","Yes, but ...","I agree with you that ..."],"followUpQuestions":["Which hobby do you like best?","Do you prefer hobbies you do alone or with friends?"],"sampleExchange":[{"role":"student_a","text":"I think video games are exciting. What do you think?"},{"role":"student_b","text":"I am not sure about that. I prefer taking photos because I can go outside."}]}', 50, 1, 1),
('ckfs2-p2-summer-activities', 'ket', '暑期活动', 'Summer activities', 'summer-holidays',
 'Do you like these different summer activities?', '你喜欢这些不同的暑期活动吗？',
 '{"source":{"book":"Complete Key for Schools 2nd Student''s Book","page":149,"section":"Speaking bank","examPart":2,"status":"reviewed"},"starterRole":"student_a","minLearnerTurns":3,"maxTotalTurns":8,"imageSlots":[{"key":"sea-swimming","label":"swimming in the sea","imageUrl":""},{"key":"pool-swimming","label":"swimming in a pool","imageUrl":""},{"key":"surfing","label":"surfing","imageUrl":""},{"key":"camping","label":"camping","imageUrl":""},{"key":"countryside","label":"visiting the countryside","imageUrl":""}],"targetLanguage":["Do you prefer ... or ...?","I prefer ... because ...","That is true.","What about you?"],"followUpQuestions":["Which activity do you like best?","Do you prefer the beach or the countryside?","Do you prefer swimming in the sea or in a pool?"],"sampleExchange":[{"role":"student_a","text":"Do you prefer swimming in the sea or in a pool?"},{"role":"student_b","text":"I prefer the sea because it is more exciting. What about you?"}]}', 60, 1, 1);
